### ISSUE TITLE
Cursor Missing after [tab] in BPartner Relation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1000]
### Type of issue
Bug
### Current behavior
When pressing [tab] after Business Partner recording in window/313 the focus does not seem to be properly in Field "Related Partner". Pressing Key leads to the dropdown. The cursor is not shown. Only if you press mouse in Field.
### Expected behavior
Shall have a proper focus and cursor in Field.

![image](https://user-images.githubusercontent.com/13365687/28029028-d7ddcb1e-659e-11e7-956b-9577221e3d18.png)

**Comment by wiadev** [comment]
@metas-mk I couldn't reproduce the error using latest master.

**Comment by metas-mk** [comment]
reproduced now w/ @wiadev in online session

**Comment by wiadev** [comment]
Reproducible when creating a new document (e.g. all fields are empty)

**Comment by wiadev** [comment]
Clarifications regarding the root cause of this issue.

Loading of dropdown bound to focus event of DIV. To achieve this div has tabIndex. This is very bad approach to bind loading event to focus of HTML element, since input which within that DIV doesn't have focus smiley and almost always has readonly status. Improper implementation caused pure mess with logic.

It's very hard to move that logic anywhere else without need to seriously rewrite that component, that's what I'm doing while aim to minimize potential impact.

Components RawList and List (container for RawList) - these two are root cause for the issue. They improperly handle focusing, changes and thus gain focus when it not needed.

Will try to avoid any regression as result of this story.

**Comment by metas-lc** [comment]
IT
1. go to window/313 and create a new BP Relation
2. set a name, press tab to go to bpartner => ok, cursor is there
3. write a bpartner, enter => address is set, and the cursor moves to the next bpartner field. It is visible and you can write the name directly OK
