### ISSUE TITLE
opening included view from action not working in picking

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1046]
### Steps to reproduce
* open picking window: https://w101.metasfresh.com:8443/window/540345
* select a row and call the pick action
* then Pick modal pops up
* select a line in left side grid and call the "Select HU to pick" action
![image](https://user-images.githubusercontent.com/1244701/28306444-fc5bb834-6ba7-11e7-81d3-27aef7bcd7d2.png)

* the action returns instructions to open a given included view but the frontend does not open it:
![image](https://user-images.githubusercontent.com/1244701/28306537-5087ad28-6ba8-11e7-9dab-882beb2fdd2c.png)

### Expected behavior
* the included view is opened
* if I click on a row on left side panel the "standard" included view is opened (exactly like it is now)

**Comment by wiadev** [comment]
This issue has been fixed but I found another problem.

please, take a look at the following screenshots.
![screen shot 2017-07-19-1](https://user-images.githubusercontent.com/18234060/28356873-7f7292d6-6ca4-11e7-9c48-2726041a8293.png)
![screen shot 2017-07-19-2](https://user-images.githubusercontent.com/18234060/28356875-81510d76-6ca4-11e7-987a-770df721eb0d.png)

please check last red row in devtools (500 server error)
if pick another line (which contains value in HUCode column) - it works fine.

Seems bug on backend side

for some reason some elements have string IDs
and this fails with 500 error
when quickAction request sent
do you see lines with empty HUCode ?
when you click on those - it throws server error
I have no idea why these lines are distinct and have string IDs while others have numeric only.

I don't know whether this is a bug. But looks suspicious for me
The only thing I can say - this is not UI side issue
I'm getting string document ID in response from backend and trying to request quickActions for this item
and it fails since it contains non-numeric ID.

**Comment by cadavre** [comment]
@wiadev afair all IDs in metasfresh are string-based.

**Comment by wiadev** [comment]
![screen shot 2017-07-19-3](https://user-images.githubusercontent.com/18234060/28358162-be7de864-6ca8-11e7-9d96-5169e7f0579f.png)
check out the above screenshot, please.
if you take a look at it, you will see that all ids are numberic but last id is string and it caused the 500 internal server error.

```
http://w101.metasfresh.com:8081/rest/api/documentView/540189/540189-7e5de7402e5a44f69533231a41ddfcd2/quickActions?selectedIds=HU1000100_P2005573
{
  "timestamp": 1500453431177,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.adempiere.exceptions.AdempiereException",
  "message": "String document IDs cannot be converted to int: HU1000100_P2005573",
  "path": "/rest/api/documentView/540189/540189-7e5de7402e5a44f69533231a41ddfcd2/quickActions"
}
```

**Comment by teosarca** [comment]
@wiadev  yup, that's a known issue, see https://github.com/metasfresh/metasfresh-webui-api/issues/496
But it shall not prevent this task.

**Comment by wiadev** [comment]
@teosarca yes, this issue was fixed itself but while I'm working on this, I found the above error.

**Comment by teosarca** [comment]
@wiadev  yup, thanks

**Comment by teosarca** [comment]
Checked #1046, but after i call the "Select HU to pick" the left side view (the included one) is empty.
Do you also get this on your workstation?

![image](https://user-images.githubusercontent.com/1244701/28635228-7dc2f1ee-7242-11e7-9d58-6246a16d085a.png)

**Comment by metas-lc** [comment]
IT
1. go to picking window, select a line and Pick
=> a modal with 2 panels opens (product on left and picking on right)
2. select open hu selection window
=> on the right side, there is a new panel to select the HUs you want to pick
3. close this hu selection window by clicking onthe product
=> you are back on the modal from step 1
4. click on the "open hu selection window" again
=> nothing happens NOK
(have to check if it's task related)
