### ISSUE TITLE
Start actions from menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#107]
e.g. following link shall start a process and not open a window

![image](https://cloud.githubusercontent.com/assets/1244701/20535303/f5ceb49c-b0ec-11e6-8c6b-3755eef9f80d.png)

**Comment by damianprzygodzki** [comment]
```
caption:"Umsatzreport Geschäftspartner"
captionBreadcrumb:"Umsatzreport Geschäftspartner"
elementId:540561
nodeId:"540738"
parentId:"1000048"
type:"report"
```

so, for the type "report" i've always should open modal with process, right? There are another types - we never discussed that, so are there any other actions that i should parsed from types in breadcrumb elements?

**Comment by teosarca** [comment]
yup. "report" and "process" share the same API.

We made this distinction here because, in future if we would like to render some icon for those menu nodes, we would need 1 icon for report and one for process.

**Comment by teosarca** [comment]
> There are another types - we never discussed that, so are there any other actions that i should parsed from types in breadcrumb elements?

atm we shall handle:
* window
* report
* process

For others i would suggest to show some "not implemented" error or something, but don't call the window API.

**Comment by damianprzygodzki** [comment]
I believe that handling "not implemented" for some window types should be covered by API. Because at least user can pass wrong window types in uri.

**Comment by teosarca** [comment]
Ok, but in this case we shall provide some API for those....

**Comment by cadavre** [comment]
Yup – we didn't yet discussed other kinds of elements than documents so it's new to implement.

**Comment by teosarca** [comment]
yup. That's why i said:
* for window is already implemented
* implement for process/report because how we have the processes REST API
* for other type, just displayed a error pop like "not implemented" or something.

**Comment by damianprzygodzki** [comment]
It is partially solved because we never planned to display modals elsewhere than MasterWindow.

What should we do here? 

I am concerned about just including this component in other container. It was made with that assumption above. It may propagates some errors or generate big amount of work - it is really hard to say for now.

Second solution is opening process like normal window - but there we need additional extension for windows - to give ability start/cancel process.

**Comment by teosarca** [comment]
IMHO when starting a process/report from main menu, we just show the overlaying parameters panel (if any) over the current window or dashboard or whatever is displayed at that moment.

It might be that i am missing something, but i don't see this as a big issue....

**Comment by damianprzygodzki** [comment]
It is not just showing overlaying panel :)

First of all, we have to connect all containers to global state. Then, we have to extract whole modal state from window reducer, because now is a part of MasterWindow model to share some data (in case of advanced edit) - this part may be impossible to achieve without loosing proper way of working, and this may cause, dividing modals on two (one connected, other no). 

It is not just 5min quickfix, thats why im asking.

**Comment by cadavre** [comment]
Are these kind of reports that normally are shown on gridview? Or document window? I mean is there other place where we can select this report/action to trigger?

**Comment by damianprzygodzki** [comment]
The first place was document window, we implemented that there in modal. Then we allow to display available actions on gridview, when some doc is selected. It is working - but only when modal is not required.

**Comment by cadavre** [comment]
<img width="1150" alt="zrzut ekranu 2017-01-17 o 10 49 09" src="https://cloud.githubusercontent.com/assets/461796/22015531/c3a5000c-dca2-11e6-9e60-9022a9cb5280.png">

> Invalid status: Invalid('Mandatory field not filled: AD_Org_ID')

What else besides 'from' and 'to' shall we fill to get this report generated?

**Comment by teosarca** [comment]
reading the error u got, u shall fill the "Sektion" (AD_Org_ID).

**Comment by metas-mk** [comment]
Hi. Just checked this issue again. Seems as if it was switched off in the meanwhile, or not? Different behavior in Navigation menu and browse whole tree.
![image](https://cloud.githubusercontent.com/assets/13365687/22855618/a7b58412-f083-11e6-9599-bca6da84bae0.png)
