### ISSUE TITLE
Implement the initial Sorting Indicator in included Tabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1147]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Sorting Indicator is missing in initially (open Window) sorted included Tabs.
#### Which are the steps to reproduce?
Open the window https://w101.metasfresh.com:8443/window/260/1000015. The first included Tab is sorted by Name initially. The OrderBy Triangle is not shown.
### What is the expected or desired behavior?
Shall be shown.

**Important:** Wait for https://github.com/metasfresh/metasfresh-webui-api/issues/541 to be finished before starting this issue.

**Comment by teosarca** [comment]
One of the first things we need to do here, and we need to coordonate between backend and frontend is to change the return type for following endpoints:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_4
* http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_3
* http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_2

At the moment those are returning an array of documents.
We need to change it to return a map of documents, so basically instead of:
```
[
  {document 1},
  {document 2},
  ... 
]
```
we shall have some:
```
{
  "result" : [ {document 1}, ... ]
}
(i.e. we are boxing the array into a map).

We have to do this because next step would be to provide the the "orderBy" property in that map.

**Comment by wiadev** [comment]
I've checked how UI renders tabs and provides default data ordering criteria.

So we have request to get layout:
/api/window/260/layout

In response we're getting:

Optional "tabs" member which is array (appears only for tabbed documents). Each entry in "tabs" could contain "orderBy" member in the same format as we have for documentView (/documentView/260).

E.g. 
"orderBy":[{"fieldName":"Name","ascending":true},{"fieldName":"M_Attribute_ID","ascending":true}]

If you can place "orderBy" value which is corresponding to default used ordering as per format stated above - this will not require any changes on UI end.

**Comment by teosarca** [comment]
@wiadev  Provided as described, just mind that the property name is called "defaultOrderBy".
Will be available on next rollout.

![image](https://user-images.githubusercontent.com/1244701/30103636-e69a1394-92fb-11e7-8885-650d1755091c.png)

**Comment by metas-lc** [comment]
IT
checked purchase order, included ab => you can see from arrow that is line asc (same as in network) OK
