### ISSUE TITLE
frontend: export view to excel

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1197]
### Type of issue
Feature request

### Expected behavior
* open any grid view, e.g. sales orders - https://w101.metasfresh.com:8443/window/143
* Menu -> Download selected (this is a new menu item that shall be introduced). When clicked, the /rest/api/documentView/{windowId}/{viewId}/export/excel?selectedIds=.... endpoinyt shall be called.

![image](https://user-images.githubusercontent.com/1244701/30372175-ae50d600-9885-11e7-954a-66b73d446e06.png)

Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/547

**Comment by PabloSichert** [comment]
Is there a way to safely assume that the current view is a grid?

I found that `type` is passed down in

https://github.com/metasfresh/metasfresh-webui-frontend/blob/0c72e61b2209208cc99c74a9458a4ea849bee1a6/src/containers/DocList.js#L105

but since it's not in the store I can't access it from components that are higher up in the node hierarchy (in this case the submenu). I think it would be worth refactoring so that this information is available when connected to the store.

- Is this feature supposed to also work with `type=list`?https://github.com/metasfresh/metasfresh-webui-frontend/blob/8796976c41b5dd6f11be5b37cd5460ba9ba36bab/src/components/header/SideList.js#L48
- Are the language keys `window.downloadSelected.caption` and `window.downloadSelected.nothingSelected`ok?

**Comment by teosarca** [comment]
hi @PabloSichert 

### Grid vs Sidelist
#### Grid
![image](https://user-images.githubusercontent.com/1244701/30548160-1ab7f248-9c9a-11e7-8191-2f802578e18e.png)
#### Side list
![image](https://user-images.githubusercontent.com/1244701/30548222-404bd948-9c9a-11e7-854d-13b73d385aed.png)


To answer to your question: whateve' i would say because the user won't have an option to export a side list anyways and when and IF we would decide that it's useful to export a side list we would just enable the option for the user.

**Comment by teosarca** [comment]
@PabloSichert 

> Are the language keys window.downloadSelected.caption and window.downloadSelected.nothingSelectedok?

Yes they are. we just have to add them on backend side.

**Comment by PabloSichert** [comment]
Hi! Great, thank you for the visualisation.

**Comment by metas-lc** [comment]
IT
1. open any window in gridview. Don't select anything. Go to actions
=> Download selected (nothing selected) readonly
2. open any window in gridview, select 1 line. Go to actions
=> download selected
3. use Download selected
=> an xls file opens, called report. It contains same columns you see in gridview, just 1 line (the one you selected), all data correctly set
4. open any window in gridview, select multiple lines. Go to actions -> use Download selected
=> same as in step 3 but you get multiple lines (the ones you selected)
5. open a window in gridview, one that has multiple pages. Select all rows (select all on this page -> select all xx items) and Go to actions -> use Download selected
=> same as in step 3, but all the data from that window is shown (you have xx rows)

swing version:
1. login on swing, open any window in grid view, go to Datei -> Exportieren
=> a save as popup appears
2. set a name.xls and press save
=> xls opens with all rows (not for the selected.. but for filtered)
