### ISSUE TITLE
Letter Window does not store template info

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1234]
### Is this a bug or feature request?
bug

### What is the current behavior?
after selecting a template the body remains empty since last build. Worked fine the build before

#### Which are the steps to reproduce?
1. open existing sales order
1. select a template in the upper right corner
1. NOK: body remains empty, template selector remains empty
1. OK: print preview works and shows correct template

![image](https://user-images.githubusercontent.com/16079655/31219705-702c6f48-a9be-11e7-9215-28e2ffba71eb.png)

### What is the expected or desired behavior?
should show body and selected template as before

**Comment by metas-mk** [comment]
Reproduced on w101. Here's the error.
![image](https://user-images.githubusercontent.com/13365687/31221804-2dbe6fba-a9c5-11e7-9b9e-3be371c7be1a.png)

**Comment by teosarca** [comment]
note to IT: regression: try creating regular documents

**Comment by metas-rc** [comment]
Results of IT

* The bug is fixed.
* I was able to select from the templates I have and their tests were displayed in the letter's text as soon as I selected them
* I was also able to add some text of my own.
* Print preview showed the text correctly
* Requests were correctly created on Create
* The pdfs were saved with the right texts in the attachments of the Requests.
