### ISSUE TITLE
When opening a document why so many calls to /menu API ?

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#124]
![image](https://cloud.githubusercontent.com/assets/1244701/20763327/3ff55b34-b732-11e6-82e9-1f6f2e754728.png)

**Comment by damianprzygodzki** [comment]
It is fetching the breadcrumb. I think that we did assume that. First we are fetching the tree for elementPath. Then i have for each of the node fetch list of nodes.

So, first call is to render 'Home menu', the three more is for the rest of path.

If you mean, by this issue, to fetch it only when first time opened, still i think that these are things that should be loaded in async way, because each of call has less than 1KB! So it is nothing, but feeling of preloaded data is much better, then always waiting for stuff.

It is not blocking any content, so i can't see bug or issue.

If you want to optimize this, you can provide everything in one endpoint, for example better structure for elementPath, without nesting elements.

**Comment by teosarca** [comment]
`If you want to optimize this, you can provide everything in one endpoint, for example better structure for elementPath, without nesting elements.`

Yup. I think the API shall provide the data in one endpoint, optimized for this case, so you would have to do one API call.
