### ISSUE TITLE
Opening a new included view is broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1243]
### Is this a bug or feature request?
bug

### Which are the steps to reproduce?
* open picking terminal window: https://w101.metasfresh.com:8443/window/540345
* select a line and call "Pick" action
![image](https://user-images.githubusercontent.com/1244701/31345755-6eb17ae6-ad1f-11e7-9bf3-830581c6a607.png)

*in the Picking modal window, make sure you have a line selected on left side and on right side (by default it is) and call "Open HU selection window".
![image](https://user-images.githubusercontent.com/1244701/31345848-b4a10788-ad1f-11e7-8379-0e502bf62dbe.png)

=> remark that the right side panel remains empty even though the frontend is fetching the layout and data.

![image](https://user-images.githubusercontent.com/1244701/31346058-83f9cf42-ad20-11e7-8984-ba801000fe3a.png)

### What is the expected or desired behavior?
the included view shall be displayed.

**Comment by teosarca** [comment]
might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1239

**Comment by ottosichert** [comment]
Can confirm it was introduced by #1239, resolving it now

**Comment by metas-rc** [comment]
Results of IT

* After I click on Pick and I select the liine, I cannot see the picking slots in the right side.
![image](https://user-images.githubusercontent.com/16001442/31452258-1068c7ca-aeb7-11e7-8490-6f44b7d8ad93.png)


* I also get the following error in the console:
> DocumentList.js:521 Uncaught TypeError: Cannot read property 'windowId' of undefined
    at value (DocumentList.js:521)
    at onMouseDown (Table.js:885)
    at Object.invokeGuardedCallback (ReactErrorUtils.js:26)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:108)
    at executeDispatchesAndRelease (EventPluginHub.js:43)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:54)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:24)
    at Object.processEventQueue

**Comment by ottosichert** [comment]
Looks like there is a new issue since last rollout:

The attributes `supportIncludedViews` and `includedView` are missing for data in Picking Terminal > Picking modal window 

![bildschirmfoto vom 2017-10-11 18-21-26](https://user-images.githubusercontent.com/1255508/31453114-4844d342-aeb1-11e7-9e76-f2ac26a73627.png)
(https://w101.metasfresh.com:8443/window/540345?page=1&viewId=540345-5a70ffcc5fe9444db0a61eeb2890a2a1)

In Picking Tray the data still has those attributes:

![bildschirmfoto vom 2017-10-11 18-21-44](https://user-images.githubusercontent.com/1255508/31453113-482765e6-aeb1-11e7-9a57-1f479eac35b6.png)
(https://w101.metasfresh.com:8443/window/540206?page=1&viewId=540206-8570050490ab451da17059cd19d5ca56)

This causes the Picking modal window to fail completely!

**Comment by ottosichert** [comment]
@teosarca Do you know if the above issue is related to https://github.com/metasfresh/metasfresh-webui-api/commit/fb46903b3de8f7ae5a444a004e99fe8c1d6af429#diff-f6787b10539a146649cf3ed8c1cbd61aR88? If so, can you take a look or tell me, where the associated `includedView` will come from?

**Comment by teosarca** [comment]
@ottosichert  might be, have to check.

**Comment by teosarca** [comment]
@ottosichert  fixed and rolled out on w101. Shall be OK now.

**Comment by metas-rc** [comment]
Results of IT2

* OK: After I click on Pick and I select the line, the picking slots in the right side are now displayed.
* OK:  When  I click Open HU selection window and I  have no HUs I get the " There are no detail rows. You can create them in this window."
* OK: If I have HUs, the HUs editor opens and all the specific actions from HUs are available for the entries.
