### ISSUE TITLE
Open ANY included view broken 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1271]
Introduced by one of the last PRs.
IMHO it's NOT related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/1258.

### Which are the steps to reproduce?
Open any window where u can open an included view,
e.g. Picking Slots - https://w101.metasfresh.com:8443/window/540206,
(but you can also check it in  Manufacturing Issue/Receipt, select a CO line and try to open the HUs to issue included view).

So, in Picking Slots, you just need to select a row and everything crashes:
![image](https://user-images.githubusercontent.com/1244701/31704762-6edba712-b3eb-11e7-898d-761d187fef2d.png)
![image](https://user-images.githubusercontent.com/1244701/31704787-82ebd592-b3eb-11e7-803f-7d732d099d0d.png)

**Comment by metas-lc** [comment]
IT
opened included views in both Picking and Manufacturing => right view is opening with no errors OK

note: Manufacturing order: quick actions are refreshed, but the view is nt vanishing. Will be fixed in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1214
Picking: i still get empty HUs in mf15 - will be solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1258

closing this task
