### ISSUE TITLE
Country selection field seems to be storted after the german country name, even we use english

### ISSUE THREAD

**Issue by amenk** [metasfresh/metasfresh-webui-frontend#1291]
### Is this a bug or feature request?

Bug

### What is the current behavior?

The country drop down sorting is wrong. Ethiopia appears within the letter A (probably because it's Äthiopien in German)

![selection_359](https://user-images.githubusercontent.com/1087128/31851893-0f2f9482-b66f-11e7-8993-ea47c5f45e72.png)

#### Which are the steps to reproduce?

Open /window/137/1000025

### What is the expected or desired behavior?

Proper alphabetic sorting

**Comment by siemiatj** [comment]
I'm just wondering if it wouldn't be easier to sort it on the backend ? I can do it on the client but since it's a list of objects, it'll not be the most efficient way of approaching this.

![screen shot 2018-04-06 at 18 11 08](https://user-images.githubusercontent.com/513460/38431850-e5e73ac8-39c5-11e8-8b09-4f9f68ee6757.png)


@teosarca @metas-ts @metasnw

**Comment by teosarca** [comment]
IMHO this is pure backend issue.
Frontend shall not change the order.
Creating it on backend.
