### ISSUE TITLE
Handling Unit Editor Sorting Error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1302]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to sort in Handling Unit Editor, then an Error pops up that Sorting is not supported. Wehn you now try to use a filter, then an empty table is shown and the Sorting Error pops up again.
#### Which are the steps to reproduce?
1. Open handling Unit Editor /window/540189
2. Press on Grid/ Table Header Column (e.g. "Gebinde Status")
3. The Sorting Error occurs
4. Press on Filter. Filter by Packing Status "Active".
5. The resulting Table is now empty. NOK
6. The Sorting Error pops up again. MOK

### What is the expected or desired behavior?
Please fix.

**Comment by teosarca** [comment]
note: the "Sorting is not supported" is thrown by backend side.
But nevertheless, the frontend shall not remember that "sort" if it failed.
i.e. Take a look on following example:
* i sorted by packingInfo => backend throws "Sorting not supported" (at this point, the frontend shall NOT remember that sorting because it did not work)
* i went to filter and tried to filter by something and press apply
=> backend throws exception because together with the filter, a sorting was also passed and that's not supported. 

![image](https://user-images.githubusercontent.com/1244701/32095495-0e72f290-bb0c-11e7-95e3-95474b2cb3bb.png)

**Comment by siemiatj** [comment]
So right now it seems that fields that are not sortable, are not clickable either. So we got rid of the first problem.

![screen shot 2018-06-12 at 16 56 37](https://user-images.githubusercontent.com/513460/41298584-f39a8a28-6e61-11e8-90d6-9e8426928eeb.png)

Using filter when data is sorted doesn't throw any errors, so can we assume this is fixed ?

![screen shot 2018-06-12 at 17 02 57](https://user-images.githubusercontent.com/513460/41298873-7d4c8154-6e62-11e8-98c3-31c966aff097.png)

**Comment by teosarca** [comment]
@siemiatj  i think yes. moving it to IT

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* sorting in HU Editor: only possible for Grid/ Table Header Column: "Code": works fine, OK
* use Filter after that: works fine, OK
* sorting in other Grid/ Table Header Columns, e.g. Gebinde Status or Product: not possible, but no error, just nothing happening: OK
* use Filter after trying to sort for e.g. Product: works finr, OK
