### ISSUE TITLE
POS processing

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#131]
Got few questions about (Wareneingang) POS. @metas-mk 

1. After selected an ordered product (ie. 240kg Frisee in 48 IFCO6416 [x5 kg] packages) there's "Quantity to use" popup where you can select one more time: CU (Frise), TU (IFCO6416) but also a LU (defaults to EUR-palette). Is this LU already assigned to the product but it's only not visible on the ordered products list? Or this assignment (48x5kg Frisee put to EUR-palette LU) is made after "Quantity to use" is "ticked green"? Asking because we ought to remove "Quantity to use" popup and go straight to CU-TU-LU management but there all above Frisee is already packed to EUR-palette LU.
2. For above: in other example we selected 2 different products and in "Qty to use" there was np TU and LU to select, but after "ticking green" "Qty to use" we saw them assigned into something called "VirtualPI". How does this work?
3. I noticed some parameters are selected *not* according to what was previously given, take a look at screens:
![a4](https://cloud.githubusercontent.com/assets/461796/20887526/494d3e00-bafb-11e6-828f-f1a0852b0a3e.png)

**Comment by metas-mk** [comment]
1.) Is this LU already assigned to the product but it's only not visible on the ordered products list? --> Yes. The LU is always underneath the TU Level and never shown in configuration.
2.) Virtual PI is something we call "no Packing material". Is used same as others with Packing material.
3.) The case above is because of temporary change of configuration in advance. Initially when selecting the Material Receipt Candidate first time, and then getting in Qty selection window, the packing material corresponds to the one in candidates line.

**Comment by cadavre** [comment]
Take a look at first mockups. At first I didn't put many notes because I'd like to check understanding of functionality only by UI.

https://collaborate.uxpin.com/70f67849d3d35fe764556268bcaf0f5bdbdcb837#/pages/64706658/sitemap
