### ISSUE TITLE
Notification display problem

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#133]
Steps to reproduce: 
* Create a sales order for G0001, with a line for a product with packing material
* COmplete the order, Create a shipment from the shipment schedules
* Go to the invoice candidates of the shipment, perform Äswahl Fakturieren (create invoice)
* There are 2 invoices created => you get 2 notifications

![notifications 13 20](https://cloud.githubusercontent.com/assets/16001442/20926919/ad567f16-bbc7-11e6-872e-3fd379e3afb2.png)

* Select one notification to open the invoice
* Open notifications again.

NOK: both last modifications have the same name, that of the notification/document you opened: 

![notifications 13 21](https://cloud.githubusercontent.com/assets/16001442/20926941/cf0b837c-bbc7-11e6-89e8-e049c08acf90.png)

* If you refresh, the notifications are displayed correctly again: 

![notifications 13 21 after refresh](https://cloud.githubusercontent.com/assets/16001442/20926951/dc7bd99e-bbc7-11e6-871e-6f168d7e5328.png)

Note: When I try it out from swagger I get the correct names for the notifications.

**Comment by Dunkat** [comment]
Hello, Could you describe the steps:
- Create a sales order for G0001, with a line for a product with packing material
- COmplete the order, Create a shipment from the shipment schedules
- Go to the invoice candidates of the shipment, perform Äswahl Fakturieren (create invoice)
- There are 2 invoices created => you get 2 notifications

screens and links will be helpful (eg. how can I create a shipment from the shipment schedules, how can I set  invoice candidates of the shipment)

**Comment by teosarca** [comment]
Note to IT: is this still reproductible?

**Comment by metas-lc** [comment]
IT: the idea is to have more than 1 documents of same type in notifications
Steps to reproduce:
- create a new sales order, add a product, complete
- go to referenced documents, select lieferdisposition-shipment schedule
- in lieferdispo window select the line and  go to actions - auswahl liefern (choose complete inout)
- repeat the steps above (because we want 2 inouts in our notifications)
- now go to notifications, and select an inout from there
- open the notifications again, you can see your inout twice
- (refresh the page and open notifications - you can see it only once)

![inout1](https://cloud.githubusercontent.com/assets/16001666/23122465/ff912048-f76c-11e6-86c6-a5cfbae367a9.png)

![inout2](https://cloud.githubusercontent.com/assets/16001666/23122467/0345e322-f76d-11e6-9e43-bc62b3195e5d.png)

**Comment by metas-lc** [comment]
IT

1. create a new sales order, add a product, complete
2.  go to referenced documents, select lieferdisposition-shipment schedule
3.  in lieferdispo window select the line and go to actions - auswahl liefern (choose complete inout)
4.  repeat the steps above (because we want 2 inouts in our notifications)
5.  now go to notifications, and select an inout from there
6.  open the notifications again
=> you can see each inout once OK
7.  (refresh the page and open notifications - you can see each only once OK)
OK
