### ISSUE TITLE
Endpoints are called several times with same parameters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#147]
NOTE: this one was broken in last iteration.

See

![image](https://cloud.githubusercontent.com/assets/1244701/21140428/a5eec6c4-c140-11e6-9de6-f036f49ca5a1.png)

**Comment by teosarca** [comment]
same thing happens with documentView too, when called from a reference.
Test case:
* open a particular purchase order
* zoom to receipt schedules (Wareneingangsdisposition)
* /documentView endpoint used to create a new view is called twice => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/21259769/99f211a8-c38b-11e6-95c4-6c40db011d94.png)

**Comment by Dunkat** [comment]
Please check if problem still exist. A lot of endpoints are changed, and looks a bit different. On my screen it looks: 

![image](https://cloud.githubusercontent.com/assets/21196151/22017492/e0835158-dcaa-11e6-93cd-c6076d364d50.png)

You can see that request '1003267' on my screen is called so many times because these are requests of changing three fields in lookup: C_BPartner_ID, C_BPartner_Location_ID, AD_User_ID

**Comment by teosarca** [comment]
Works fine. Thanks.
