### ISSUE TITLE
Dashboard breadcrumb menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#148]
Dashboard Breadcrumb Menu wrong since last rollout.
Shows Home + last path with concatenated "/Dashboard". Should be Home"/ Dashboard". Further on, if you press on breadcrumb then you cannot navigate.

see https://github.com/metasfresh/metasfresh-webui/issues/95

**Comment by damianprzygodzki** [comment]
Cannot reproduce. Could you provide case?

**Comment by metas-mk** [comment]
@damianprzygodzki yes, but please be aware this issue is labeled as **metasfresh turn** because it seems to be backend problem.
**case:** open window ID 143. you will see breadcrumb like "home/vertrieb/auftrag".
Then go to navigation menu and press "dashboard". dashboard will be opened with breadcrumb like "home/vertrieb/auftrag/dashboard" instead of "home/dashboard".

**Comment by teosarca** [comment]
imho it's not backend.

**Comment by metas-mk** [comment]
ok, then. I see that @damianprzygodzki has taken the label out already. ;-) thanks.
