### ISSUE TITLE
Cannot open "Create purchase orders" modal view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1481]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
(This is a general issue, but I just found it when i've tried to open "Create purchase orders" modal)

* create or open a sales order, e.g. https://w101.metasfresh.com:8443/window/143/1000291
* select it's lines 
* from Action try to call "Create purchase orders"
* nothing happens => NOK

### What is the expected or desired behavior?
Check the console. There is an error.
NOK1: if there is an error when trying to run a process, that error shall be displayed to user. Atm it's displayed only in console (Split off in this issue https://github.com/metasfresh/metasfresh-webui-frontend/issues/1493)

NOK2: (the actual one) The process instance is not created correctly, that's why it's failing.
Take a look at "documentId" field. There we have the included document's ID instead of our header document ID.
![image](https://user-images.githubusercontent.com/1244701/34668539-85c91c90-f476-11e7-9209-54766daca12d.png)

**Comment by metas-mk** [comment]
The issue described above does not only happen with this action/ process. A lot of other menu actions/ processes are affected as soon as sublines are selected.

**Comment by metas-lc** [comment]
IT
tested: 
create purchase orders OK
group lines OK
dunning jasper OK
create request for bpartner OK
change user password OK
generate shipment OK
create invoice OK
(couldn't test rerunning transform process on LU because the quickactions are not sent anymore. But we have another task for it https://github.com/metasfresh/metasfresh-webui-frontend/issues/1487)
add hu to trnsportation in picking clearing - not working well: created task https://github.com/metasfresh/metasfresh-webui-frontend/issues/1495

**Comment by metas-ts** [comment]
just found that this issue is in `release`, aparently i forgot to flag it accordingly
