### ISSUE TITLE
Filter Dropdown dynamically extend height when dropdown list selected

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1514]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when using a dropdown list that is located at the end of a filter list, then it happens that there is not enough space/ height in the filter list and a scrollbar in the filter list is shown. The dropdown list is cut off.
#### Which are the steps to reproduce?
Open, try and see in window/143 and in window/540092.
### What is the expected or desired behavior?
Please create a solution so that the filter list is extended to the needed height. If the filter list still dows not have enough height to avoid a vertical scrollbar, then scroll automatically so that the dropdown list is not cut off.

![image](https://user-images.githubusercontent.com/13365687/35139999-d4c0eb66-fcf5-11e7-8bd6-458c10e8852d.png)

![image](https://user-images.githubusercontent.com/13365687/35140105-48a38c8c-fcf6-11e7-88cb-732382a5841a.png)

**Comment by metas-mk** [comment]
@wiadev Quick Check done. Found this issue when scrolling down with opened dropdown list
![image](https://user-images.githubusercontent.com/13365687/35259247-054b6376-0005-11e8-9ff7-07fabebb576f.png)

**Comment by metas-mk** [comment]
@wiadev another quick check. Dropdowns in Lookup widgets are missing.
![image](https://user-images.githubusercontent.com/13365687/35261457-78731082-0010-11e8-8847-8b5094a54754.png)

**Comment by metas-lc** [comment]
IT
besides what @metas-mk wrote in the last 2 comments, i noticed the following:
1. filters: if you try to set something in a filter that is dropdown (e.g. Preissystem from the picture above), nothing happens NOK 
2. if you go in HU Editor (/window/540196 - receive HUs) and press on dropdown attributes, nothing drops down NOK
![image](https://user-images.githubusercontent.com/16001666/35274438-bd33aacc-0044-11e8-9bf8-09e9668d4e36.png)

**Comment by teosarca** [comment]
@wiadev  i've stumbled on this https://github.com/metasfresh/metasfresh-webui-frontend/pull/1530/files#r163853852 . I think we shall not use hardcoded  stuff.

**Comment by metas-lc** [comment]
dropdowns in tabs don't work
e.g.
https://w101.metasfresh.com:8443/window/123/2156423
tab vendor, try to change the pricelist
![image](https://user-images.githubusercontent.com/16001666/35451226-3327cd52-02cb-11e8-88ad-d852e7699c0b.png)

**Comment by metas-lc** [comment]
1. dropdown in filters are ok OK
2. dropdowns in HU editor are fine OK
(you can't set date in hu editor, but it will be fixed by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1504) OK
3. dropdown for attributes (like bill of material window) is fine. You can't set one but it will be fixed by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1536 OK


remaining todo: dropdown in tabs (see the comment above)

**Comment by metas-mk** [comment]
@siemiatj this is the remaining issue here
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1514#issuecomment-360842709
<-- dropdowns in subtabs cannot be selected and saved via mouseclick

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

1. dropdown in filters are ok: (checking in chat):
  * in IC window filter, the dropdown for filter shipment / receipt only ever shows 10 results in the dropdown, is that ok?
  * the filter for doc type, in sales order window, still seems a bit cut off to me, is that ok?
2. dropdowns in HU editor are fine: OK (date in HU Editor can also be set again)
3. dropdown for attributes (like bill of material window) is fine: OK (You can't set one but it will be fixed by #1536)  OK
4. dropdown in tabs selectable with mouse click: OK

**Comment by metas-dh** [comment]
Update:
* selecting country from dropdown not working with mouse click, https://github.com/metasfresh/metasfresh-webui-frontend/issues/1552

**Comment by metas-dh** [comment]
open issues in follow ups, see above; closing this one.
