### ISSUE TITLE
Empty patches in documents

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1584]
### Is this a bug or feature request?
bug
### What is the current behavior?
empty patches after opening a document
#### Which are the steps to reproduce?
open sales order.. or shipment disposition: https://w101.metasfresh.com:8443/window/500221/1004456
=> notice there are about 12 empty patches

![image](https://user-images.githubusercontent.com/16001666/36096263-510b2ab8-0ffe-11e8-909c-8b57aab1d844.png)

**Comment by teosarca** [comment]
found another case:
* open Accounting Export Format: https://w101.metasfresh.com:8443/window/540414/540000
* right click on first included line and call Advanced
* the error you get is because frontend tries to PATCH a readonly record
![image](https://user-images.githubusercontent.com/1244701/36505482-5685caf6-175c-11e8-964b-7d191c107c20.png)
![image](https://user-images.githubusercontent.com/1244701/36505601-bab46b5e-175c-11e8-80f3-19b233b9e557.png)

**Comment by teosarca** [comment]
found another one in HU editor attributes:
![image](https://user-images.githubusercontent.com/1244701/36915998-4e1b178a-1e5b-11e8-9641-108dff5d7cb0.png)

**Comment by siemiatj** [comment]
Checked all those cases and it's not reproducible in any of them.

**Comment by metas-lc** [comment]
checked again. Could not reproduce. Moving it to done
