### ISSUE TITLE
Color Indicator Widget functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1603]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to have a color indicator Field in metasfresh, e.g. a field with a colored background or a field with content that is just a small green, yellow or red circle (nice to have).
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Following scenario:
- Possibility to add a property to a field that has the background color/ text color. This way we can still use everything else like the filter, sorting without changes.
- A nice to have solution would be a new widget, that just shows the color information as a circle. In such cases, we would also need the possibility to sort by color and filter by color.

**Comment by teosarca** [comment]
update:
Introduced widgetType:Color.
The value is a string which has the standard hex color format, e.g. #aabbcc.

**Comment by teosarca** [comment]
Prepared a test case: https://w101.metasfresh.com:8443/window/143/1000616
![image](https://user-images.githubusercontent.com/1244701/38659877-ffb609b2-3e33-11e8-8772-aaea496b5bae.png)


To prepare this test case i did:
* created a new sales order and a new sales order line
* checked which is the order ID, tab ID and the line ID
* patched the order line:
```
curl -X PATCH --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[ \ 
   { \ 
     "op": "replace", \ 
     "path": "NoPriceConditionsColor_ID", \ 
     "value": "#FFAABB" \ 
   } \ 
 ]' 'http://w101.metasfresh.com:8081/rest/api/window/143/1000616/187/1001035?advanced=false'
```
(by using swagger: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/patchIncludedDocumentUsingPATCH)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK: if pricing conditions are required and there are no pricing conditions for an order line, the color is set to a small circle of the color I defined in the sys config.

![image](https://user-images.githubusercontent.com/16001442/39304009-ddc0e8a8-4960-11e8-896e-3f93098c9f4a.png)

**Comment by metas-ts** [comment]
hi @metas-mk @metas-rc @teosarca how does configuring this feature work?
How does one define the color and when it is set?
Can someone please add some screenshots?

**Comment by metas-rc** [comment]
These are the colors that are currently available in our app dictionary: 

![image](https://user-images.githubusercontent.com/16001442/39564371-a270958a-4ebc-11e8-9349-c76775b20f65.png)


In order to start this feature, we will have to set a color name (It must be a correct name from the AD_Color table) in the following sys config: 


![image](https://user-images.githubusercontent.com/16001442/39564412-d01518ee-4ebc-11e8-990b-b93a9e4139b4.png)


Example: I want the color to be red: 

![image](https://user-images.githubusercontent.com/16001442/39564437-e548006e-4ebc-11e8-9038-9fe4cc9b653a.png)

I created an orderline with no schema break.
On my local, it looks like this: 

![image](https://user-images.githubusercontent.com/16001442/39565859-3ed6cd40-4ec2-11e8-9a68-dabd36ecadcd.png)

A while ago I tested it on our testing system and I made several lines with different colors, by changing the sys config over and over. . It looked like this: 

![image](https://user-images.githubusercontent.com/16001442/39565907-6614bf16-4ec2-11e8-8b2e-b93a33144977.png)
