### ISSUE TITLE
Camera barcode reader for Tablet/ mobile device

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1609]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have the possibility to read Barcodes via the built-in camera of a tablet or other mobile device.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
It shall be possible to use the built-in camera for barcode reading and recognition. Shall be usable in Lookup widgets as action parms and also in barcode overlay.

**Comment by metas-dh** [comment]
Results of IT2
tested in testing instance dev19 (5.53.1) for tablet

* Camera barcode reader available: checked in window/540373: Camera barcode scanning action was available, but my tablet camera was not accessed: not sure if this is due to my crappy tablet or not, @metas-mk : was this already tested by you / the customer?

**Comment by siemiatj** [comment]
Did you get a popup asking for permissions to use the camera ?

**Comment by metas-dh** [comment]
checked with metas-mk: works fine, already used by customer, so moving it to done.
