### ISSUE TITLE
Batch entry product drop-down too narrow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1614]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In the batch entry dropdowns for products, we have put additional information about the current stock. With some products with long identifiers, the stock information is cut off.
#### Which are the steps to reproduce?
Open sales order window https://w101.metasfresh.com:8443/window/143/1000479 and see.
### What is the expected or desired behavior?
For Batch entries, it shall be possible to have the drop-down in the whole length of the combined field (product + packing instruction). Perhaps we need some additional property via backend about this?

![image](https://user-images.githubusercontent.com/13365687/36464510-92bd7ce4-16d0-11e8-8b5e-cb520cfd5495.png)

**Comment by PabloSichert** [comment]
Since there's more fields now, I guess it would make sense to dedicate two rows for the inputs.

Having a property from the backend would also help if this is a special case for the lookup component. Could you tell me on which other sites the lookup is used, so I can check that it doesn't break there?

Are there any updates on the requirements / backend task?

<img width="1066" alt="Sales order - order lines" src="https://user-images.githubusercontent.com/4450694/40428680-1c4e089e-5ea1-11e8-9f6c-4c9c5d7973d7.png">

**Comment by siemiatj** [comment]
I guess this is fixed with #1910

**Comment by metas-dh** [comment]
checked in mf15:

the drop-down is displayed in the whole length of the combined field (product + packing instruction) for batch entries: OK

![2018-09-28 16_02_42-metasfresh](https://user-images.githubusercontent.com/18696715/46213169-2f109180-c338-11e8-9146-2e1026c8a655.png)

closing this task
