### ISSUE TITLE
Material Cockpit Filter Name + switch date = invalid name

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1624]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when using the Material Cockpit and filtering a Product name, then switching through dates. An Invalid Date" filter is set to Product name filter.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall not change the name parm when switching date.

**Comment by metas-ts** [comment]
Hi @siemiatj 
I think that the error occurs because the API returns the two filters in the reverse order from which they were returned the first time.
Here is an API response:
```json
{
	"windowId": "540376",
	"viewId": "540376-ff74b3a3e7e541a491b717fd7721cf4c",
	"size": 1,
	"filters": [{
		"filterId": "materialCockpitAllParamsFilter",
		"parameters": [{
			"parameterName": "ProductName",
			"value": "conv",
			"valueTo": null
		}]
	},
	{
		"filterId": "materialCockpitDateOnlyFilter",
		"parameters": [{
			"parameterName": "DateGeneral",
			"value": "2018-02-24T00:00:00.000+01:00",
			"valueTo": null
		}]
	}],
	"type": "540376"
}
```
It seems as if the frontend ignores the `filterId` property and just applies the parameter in whatever ordering the the list comes with.
We can look into making the API send a list whose ordering is alligned to the filters' layout, but i guess it would be better to let the frontend use the filterId property..
Btw, please feel free to propose a response that's easier to digest for the frontend.

**Comment by metas-lc** [comment]
IT
1. open Material Cockpit window / 540376
2. write something in product filter (e.g. sala), apply
=> data is filtered
3. change the date filter using left and right buttons
=> date is set correctly OK
=> product filter is still as you set it (sala) OK
4. change the date manually 
=> date is set correctly OK
=> product filter is still as you set it (sala) OK
