### ISSUE TITLE
Expand Button behavior and layout proposal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#163]
Expand Button behavior and layout proposal
- when pressing expand button for included tabs, then show the included tabs in "fullscreen". same layout/ design as if included (just seems to move up to header and is show "expanded")
- proposal: when expanded then automatically activate the fast line/ batch entry fields and put the cursor/ focus automatically in the first recording field
- proposal: id we show the tabs also ion expanded view, should the expand button in included tab not be "outside" the tab area (not on tab), because it manipulates/ expands all tabs at once.
- in expanded mode, same as in included mode, the recording area shall be shown expanded to 100% of the screen height - keeping the top bar/ header (edit after @cadavre response)

**Comment by cadavre** [comment]
> when pressing expand button for included tabs, then show the included tabs in "fullscreen". same layout/ design as if included (just seems to move up to header and is show "expanded")
Agree.

> proposal: when expanded then automatically activate the fast line/ batch entry fields and put the cursor/ focus automatically in the first recording field
After you introduce "fastline available" into particular windowType we will always show fastline by default following small (icon only) "Add" button. If no fastline will be available a bigger "Add" button (with icon and label) will be shown. There will be no switch to display it, because it collides with main assumption – being "fast".

> proposal: id we show the tabs also ion expanded view, should the expand button in included tab not be "outside" the tab area (not on tab), because it manipulates/ expands all tabs at once.
It might be on tabs level but it's "new" place for button we didn't introduced yet. I believe this button inside of tab is still fine.

> in expanded mode, same as in included mode, the recording area shall be shown expanded to 100% of the screen height.
But keep topbar.

**Comment by metas-mk** [comment]
@cadavre agree. thanks for the feedback.
