### ISSUE TITLE
Detailed adjustments of User Interface for tablet media size

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1692]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The first iteration of UI adjustments has already improved the usage of metasfresh with a tablet media size.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The following details shall be further improved:

Handling Unit Editor:
- cut off calendar widget
- right view initially opened 50%
- green quick action button back (in general)
![image](https://user-images.githubusercontent.com/13365687/37654307-ebd89df0-2c41-11e8-8629-92b7ac857fed.png)

Picking Window:
- right view initially opened 60%
- take out "prefix in filter "Filter by:"
- green quickaction button (in general)
- Action dropdown wider, so that mostly just has 1 line for action
![image](https://user-images.githubusercontent.com/13365687/37654422-44f50310-2c42-11e8-8cfa-0cfd99818d85.png)

![image](https://user-images.githubusercontent.com/13365687/37654511-a5c9d756-2c42-11e8-915e-3ded8a45acd2.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / testing instance dev18 (5.52.1) for tablet

Handling Unit Editor:

* cut off calendar widget: OK
* right view initially opened 50%: it looks more like 70%, imho the right side with the attributes is too wide (in window on desktop it looks like 50%, which i think is too wide as well): NOK

![image1](https://user-images.githubusercontent.com/18696715/38372334-d8e476f6-38ee-11e8-8e71-ff2dad6be30b.jpeg)


* green quick action button back (in general): OK

Picking Window:

* right view initially opened 60%: OK
* take out "prefix in filter "Filter by:":  it's ":Scan Locator": i think OK
* green quickaction button (in general): OK
* Action dropdown wider, so that mostly just has 1 line for action: OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15 / testing instance dev19 (5.53.1) for tablet

Handling Unit Editor:
* right view initially opened 50%: OK

Picking Window:
* right view initially opened 60%: OK
