### ISSUE TITLE
Action button not properly displayed in Transportation Order window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1843]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The action button in in Transportation Order window/540020 is not displayed correctly:

![2018-06-13 08_29_16-metasfresh](https://user-images.githubusercontent.com/18696715/41337923-f0289fee-6ef0-11e8-95f6-46a5304317d7.png)

#### Which are the steps to reproduce?
Check and see.

**Comment by metas-lc** [comment]
IT
currently, the button looks like this: 
![image](https://user-images.githubusercontent.com/16001666/41714568-61368714-7559-11e8-92b5-57c5b0ed359d.png)
and i was expecting the one for draft
![image](https://user-images.githubusercontent.com/16001666/41714583-71fb0566-7559-11e8-99a4-623627f83822.png)
line we have in e.g. sales order

note: i will keep this task on me since creating transportation order is not working well on webui. Will check again, later

**Comment by siemiatj** [comment]
Problem is client doesn't get the status value from the backend, so there's nothing I can show there. It must be some edge case.

**Comment by metas-lc** [comment]
checked the network and docStatus is missing from fields. Created task: https://github.com/metasfresh/metasfresh-webui-api/issues/990
