### ISSUE TITLE
Searching in BPartner field from order is not working

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1853]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot use the bpartner search field in order
#### Which are the steps to reproduce?
1. go to sales order (window/143), create a new one, try to add bpartner test kunde
=> the bpartner is not found NOK
=> the button to create a new bpartner is missing NOK
![image](https://user-images.githubusercontent.com/16001666/41705991-4e4d969e-7543-11e8-8bdc-78369863740a.png)

### What is the expected or desired behavior?
shall work as before

**Comment by siemiatj** [comment]
I can't reproduce this neither on local or w101 : 

![screen shot 2018-06-21 at 11 26 38](https://user-images.githubusercontent.com/513460/41710430-eed51a22-7545-11e8-85a3-c486335bc13f.png)

![screen shot 2018-06-21 at 11 26 09](https://user-images.githubusercontent.com/513460/41710454-fc1a925c-7545-11e8-9df3-322772e4ef2d.png)

I think it might've been due to teo working on elasticsearch and probably there were no results returned. I'm creating a PR with improved data checks in place to prevent this error in the future.

**Comment by metas-lc** [comment]
IT
1. new sales order, add bpartner that doesn't exists 
=> no errors in console OK
=> button to create new Business Partner appears OK
