### ISSUE TITLE
[alt]+Enter not working as before

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1871]
### Is this a bug or feature request?
Bug
### What is the current behavior?
[alt]+Enter is not working as it used to:
1. Material Receipt Candidates, window/540196:
=> [alt]+Enter when trying to call receive / transform / print (labels) action, after setting e.g. qty to receive or selecting a certain transfrom action in the modal window: whole HU Editor is closed
2. Manufacturing Order, window/53009:
=> [alt]+Enter when trying to call receive action, after setting qty to receive in the modal window: whole HU Editor is closed

=> clicking the ```Start``` button with mouse works fine!

(checking for more examples)
#### Which are the steps to reproduce?
Try and see.

**Comment by metas-lc** [comment]
IT
1. go to receipt candidates window, select a line and run Receive HUs action, set qtys, press alt+enter
=> HU Editor opens (Start button) OK
2. select the TU, run Transform action, press on alt+enter
=> Mandatory field Action not filled OK
3. set action: TU to new LU, set the LU, qty, press alt+enter
=> TU was transformed OK
=> back in hu editor OK
4. select the LU, run a label, press alt+enter
=> label was crated OK
=> back in hu editor OK
5. while you are in hu editor press alt+enter (for Done)
=> hu editor closes OK
.
6. create/ complete a new manufacturing order
7. go to grid view and select your line - run Issue/ Receipt
8. select a CO product, open hus, transform one like in step 3
=> TU was transformed OK
9. select the main product (MP), run Receive HUs, add TU and LU, qtys, press on alt+enter
=> hu was received OK
 .
10. go to handling units window, select an LU, move to another warehouse
11. select the wh and press alt+enter
=> HU moved OK
12. select a TU, use transform, move it to existing LU, press alt+enter
=> TU was moved on the existing LU OK
.
13. run a report from menu, like Business Partner Revenue, set all mandatory fields, press alt+enter
=> pdf was created OK 
.
14. also tested esc (cancel) instead of start
=> still works OK
