### ISSUE TITLE
Show field-description in tool-tip instead of field-caption

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#1953]
### Is this a bug or feature request?
FR
### What is the current behavior?

If you hover over the field name, the brower aparently shows the `caption` properties value

![image](https://user-images.githubusercontent.com/1264789/45156592-fa009b80-b1de-11e8-9e52-5b2f2cd93a3c.png)

#### Which are the steps to reproduce?
try it

### What is the expected or desired behavior?

instead the `description` should be shown

**Comment by teosarca** [comment]
We reverted this one last night because in some cases the field captions were missing.

e.g.
* check https://w101.metasfresh.com:8443/window/139
* check https://w101.metasfresh.com:8443/window/143 filter captions

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Show field-description in tool-tip instead of field-caption:

* field-description in tool-tip instead of field-caption where description available: e.g. "Warehouse" in sales order: "Storage Warehouse and Service Point" in tool-tip: **OK**
* field-description displayed in menu language: **OK**
=> trl missing for some description, e.g. "Drop Shipment" in sales order: only en_US description available
* field-caption is displayed in tool-tip if there is no description available: e.g. "Diff. unloading point" in sales order: **OK**
* working in single and grid view: **OK** for fields like e.g. "No." or "Business Partner"
=> neither field-caption nor description was displayed for the Filters, in grid view, e.g. in window/143: Default Filter showed only "Filter", while Filter Date did not show anything: is that OK?
