### ISSUE TITLE
Fix dropdown layout issues

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#202]
i.e.
* make the dropdown wider
* make sure items are not half cut when displayed

![image](https://cloud.githubusercontent.com/assets/1244701/22056862/d00ef12c-dd6a-11e6-81b2-e9b71a0a27c2.png)

**Comment by damianprzygodzki** [comment]
I am really not sure if this are layout issues.

We cannot make dropdown wider than input. What can i do here is to expand inputs to 100% width of available place.

**Comment by metas-mk** [comment]
ah, understood. thx for the info. lets still think about it. not prioritized for now.

**Comment by cadavre** [comment]
@metasfresh have you thought about removing this identifier part from beginning of the string? P0023464_... doesn't look like a useful name.

@damianprzygodzki I'm not sure if ellipsis will work because there might be some important data hidden. That would work well for keeping single line dropdown (it actually should be this way), but it would must go in pair with above ProductID removal.

**Comment by damianprzygodzki** [comment]
@cadavre thats why there is no ellipsis til today ;) im trying find solution to reported issue.

**Comment by teosarca** [comment]
> @metasfresh have you thought about removing this identifier part from beginning of the string? P0023464_... doesn't look like a useful name.

Yes it is very useful information. ERP users are used with codes and usually they will type the "code" instead of name.

**Comment by teosarca** [comment]
Another thing of which we need to take care here is the dropdown item which is cut. i.e. take a look at the last item. Suggestion:
* make sure we are not cutting items
* and/or increase the height of that dropdown

**Comment by cadavre** [comment]
Then we will go with ellipsis.
