### ISSUE TITLE
Chrome feature overwrites country selection in Lookup

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2103]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When typing country in Lookup widget, then chrome overwrites the dropdown with an own Feature, showing possible Addresses.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall show the country selector again. Please also check other Address selectors for similar cases.

![image](https://user-images.githubusercontent.com/13365687/49851926-e4ed6700-fde2-11e8-83e6-c79b5d4e8e31.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / release

* country selection is displayed in Lookup, not overwritten by Chrome feature: was correctly displayed in e.g. country lookup in location tab, bpartner, or location in marketing contact: OK
=> could not test the exact case above since we the window is customer specific and the task is not rolled out at customer yet!

**Comment by metas-dh** [comment]
checked again in customer db:

=> country selection is displayed in Lookup, not overwritten by Chrome feature: was correctly displayed in the filter shown in the pic above: OK
