### ISSUE TITLE
Optimizing Table Data space and descriptions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#217]
Optimizing Table Data space and descriptions
Low Prio.

![image](https://cloud.githubusercontent.com/assets/13365687/22175004/addd5a38-dfec-11e6-8c55-bed74ce2e658.png)

**Comment by cadavre** [comment]
We had this topis already I believe. We provide 3 different **static sizes** of columns today because we don't want to set column width to fit content (imagine when there are 100 entries with "xx" and just one with "xxxxxxxxxxx" – it takes all the white space.

What do you mean with red boxes in "Bestellte menge" and "Auf Packzette"?

**Comment by metas-mk** [comment]
@cadavre Red boxes in "Bestellte menge" and "Auf Packzette"? means that the Headlines are just cut off. These 2 could be solved via shorter column names for example.
Problems occur with some fixed current widths of certain columns. For example, in Product Price window window/540325 we have a column "Product" which is a combined field w/ Product and Packing Material. In Grid view only makes sense if the user also sees the packing material. Can we find a more flexible solution for this case?

**Comment by cadavre** [comment]
May I ask you to create Excel spreadsheet where you'll "simulate" how you'd like this kind of table to behave? We'll try then to implement this.

**Comment by metas-mk** [comment]
Discussed in Jour Fix.
Provide the size override for column layout if different for the given window: S, M, L
