### ISSUE TITLE
Views: Render header properties

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2223]
### Is this a bug or feature request?
FR

#### Which are the steps to reproduce?
* open 
`Kommissionier Terminal v2 (Prototyp)` (http://localhost:3000/window/540485)
* select a line and call Pick action

![image](https://user-images.githubusercontent.com/1244701/54757334-a8f04c00-4bf2-11e9-91e8-14dbaa4afb28.png)

### What is the expected or desired behavior?
Check the response of `GET /rest/api/documentView/picking_v2_productsToPick/....` endpoint.
If there is an `headerProperties` property then please render it's entries near the view name.
Each entry shall be rendered like github's labels. For the start, use table header's color (i.e. #9BAFBC).
Those properties shall be responsive.

![image](https://user-images.githubusercontent.com/1244701/54757694-6da24d00-4bf3-11e9-935e-0a8971bd2f55.png)

**Comment by siemiatj** [comment]
Works ok. But I'm not sure about styling. I imagined something more along those lines:

![Screen Shot 2019-05-21 at 14 17 55](https://user-images.githubusercontent.com/513460/58095460-566fe380-7bd3-11e9-9b5e-8e9bc78bb370.png)

instead of current

![Screen Shot 2019-05-21 at 14 19 16](https://user-images.githubusercontent.com/513460/58095497-6d163a80-7bd3-11e9-8235-f091b445d302.png)

@teosarca wdyt ?

**Comment by metas-dh** [comment]
IT in me03.
