### ISSUE TITLE
Wrong Button color after first Date click in Range Widget

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2232]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When selecting the first Date in Range widget, the Button color changes from correct brand color to the wrong color.
#### Which are the steps to reproduce?
Open, try and see in any Range widget Filter.
### What is the expected or desired behavior?
Pls. Fix
Example /window/143

![image](https://user-images.githubusercontent.com/13365687/55155469-b8721680-5157-11e9-8840-11f6c29fa43d.png)

**Comment by oliviupis** [comment]
@metas-mk Can you please specify which color is the correct one?

**Comment by teosarca** [comment]
shall be our metasfresh logo green

**Comment by metas-dh** [comment]
Results of IT1
tested in releasetest

1. selecting the first Date in Range widget, the Button color has the correct brand color (read-only since only 1st date is set): **OK**

![2019-06-13 08_18_04-Metasfresh](https://user-images.githubusercontent.com/18696715/59408362-2ec80180-8db4-11e9-91d5-94968e419539.png)

2. selecting the 2nd Date in Range widget, the Button color also has the correct brand color (not read-only anymore): **OK**

![2019-06-13 08_18_18-Metasfresh](https://user-images.githubusercontent.com/18696715/59408372-34254c00-8db4-11e9-8dc6-1571f9e659f8.png)
