### ISSUE TITLE
frontend: Image WidgetType support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#228]

**Comment by teosarca** [comment]
(check the screenshot below)
When the widgetType is Image we shall render a component which allows us to preview current set image and also upload a new image.
Field's value will always be an ID, the imageId.

To fetch an image by imageId, use endpoint http://w101.metasfresh.com:8081/swagger-ui.html#!/image-rest-controller/getImageUsingGET .

To upload a new image, use endpoint http://w101.metasfresh.com:8081/swagger-ui.html#!/image-rest-controller/uploadImageUsingPOST.
In this case the new imageId will be returned.


About the Image widget, it shall:
* display the current image if any
* have (small) buttons to take the picture using webcam, upload an image.
Those small buttons shall look similar like we have on social networks Posting form. e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/22398794/d7df42b4-e597-11e6-8554-e44d257de4ec.png)


Example where you can find the Image widget.
![image](https://cloud.githubusercontent.com/assets/1244701/22398723/e1f6f28e-e596-11e6-8e0b-3f2fa963a08f.png)

**Comment by cadavre** [comment]
If it comes to taking picture from camera, this is on which browsers can we support it:
http://caniuse.com/#feat=stream

**Comment by teosarca** [comment]
IMHO, it's ok for now

**Comment by cadavre** [comment]
@teosarca @metas-mk where can we expect Image widget? Shall we except it might be displayed also in table cell or in ProductAttributes? Or it will be just in documents and modals?

**Comment by teosarca** [comment]
@cadavre  See the attached picture, i.e.
* open Wareneingangdisposition (aka receipt schedule): http://w101.metasfresh.com:8090/window/540196
* select a line
* action menu
* Foto action

**Comment by cadavre** [comment]
I saw it, but my question wasn’t about it. I was asking if you have in mind
that this widget would appear somewhere else in near time.


dnia 1 lutego 2017 o 12:53:23, Teo Sarca (notifications@github.com) napisał:

@cadavre <https://github.com/cadavre> See the attached picture, i.e.

   - open Wareneingangdisposition (aka receipt schedule):
   http://w101.metasfresh.com:8090/window/540196
   - select a line
   - action menu
   - Foto action

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/metasfresh/metasfresh-webui-frontend/issues/228#issuecomment-276639256>,
or mute the thread

**Comment by teosarca** [comment]
theoretically can be in any window.

@metas-mk  do you have any practical example? (might be Organization window?)
