### ISSUE TITLE
Location editor button called "edit attributes"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#229]
Location editor button called "edit attributes"
- should be a localized name for "Location" or "edit Location"
Don't know if it's frontend or backend issue.
Can be reproduced in window /window/123/ in subtab 5 Adresse/ Location.

![image](https://cloud.githubusercontent.com/assets/13365687/22397943/c1254ac4-e57d-11e6-90ae-2add6144b4fd.png)

**Comment by cadavre** [comment]
It's probably both – backend and frontend. Looks like hardcoded value in frontend, but it would be because of no text given from backend. @teosarca could you confirm?

But to be honest I don't see point of changing this as long as you have label na left, and in fact fields you see are attributes. :)

**Comment by teosarca** [comment]
I guess backend, at least, provides the "emptyText".... but i think it's not suitable here.
(It might be that we will need to introduce another property, not sure.....)

But, nevertheless, having "Edit attributes" on the Location field is NOT OK.
As a quickfix i would suggest to display there on "Edit".

@metas-mk  wdyt?

**Comment by metas-mk** [comment]
Tested. Solved. The Button is now called "Edit" as long no data is stored.

**Comment by metas-mk** [comment]
Add to release notes.
