### ISSUE TITLE
Implement ProcessButton widget

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#250]
Button Widget in Subtab Lines and/ or Advanced Edit
- Is a process Button that has to Open a Process Parms Widget and start underlying Process.

![image](https://cloud.githubusercontent.com/assets/13365687/22658462/718d5730-ec9a-11e6-84b2-af1dd62312b3.png)

**Comment by cadavre** [comment]
@teosarca how shall we handle this from API?

This widget is rendered by:
```
{
displayed:true
field:"ProcCreate"
mandatory:false
readonly:false
valid:true
value:"N"
widgetType:"Button"
}
```

Shall you attach `processId` into widget?

**Comment by damianprzygodzki** [comment]
Whatsmore we have not sth like "Process Parms Widget". All processes are handled by modals.

**Comment by teosarca** [comment]
need to think....

**Comment by damianprzygodzki** [comment]
In referenced issue, what we have to remember, that buttons should handle redirecting too.

**Comment by teosarca** [comment]
I've introduced a new widget type, called ProcessButon.
It shall be rendered as Button widget but:
* it shall display the element caption, always (instead of "value")
* when button is clicked it shall start the given process instead.
* readonly means button is not pressable (disabled)
* mandatory shall be ignored
* displayed shall be considered, so if displayed=false, the button shall not be displayed

## Running the process
A new property was introduced in element, called "buttonProcessId".
When the button is clicked the process identified with that ID shall be started.
See http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/createInstanceFromRequestUsingPOST .

In the create request, along with documentType and documentId two new properties shall be provided if the button is on an included document: the "tabId" and "rowId".

![image](https://cloud.githubusercontent.com/assets/1244701/23144540/fd12bb7e-f7d0-11e6-8f36-c9d84c6251d8.png)

**Comment by teosarca** [comment]
API is ready.

**Comment by metas-rc** [comment]
Results of IT1: OK

Tested on http://w101.metasfresh.com:8090

The button works correctly, no error in the console. 

The backend test was also performed, the process is working correctly. See Daniela's results on https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23161.md

**Comment by teosarca** [comment]
IMHO it's not OK.

Test case:
* opened http://w101.metasfresh.com:8090/window/540321/2008396
* right click on one of the included rows, advance edit
* pressed the process button
=> the Advanced edit modal was closed => NOK. it shall stay

**Comment by damianprzygodzki** [comment]
There is no option to have two modals opened at the same time. 
Processes needs opened modal too.

**Comment by teosarca** [comment]
As we talked, this issue shall be solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/430
