### ISSUE TITLE
Low prio: freeze device value while hovering the button

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#255]
![image](https://cloud.githubusercontent.com/assets/1244701/22713934/0afb748a-ed93-11e6-8c1e-62fc620c23e3.png)

**Comment by cadavre** [comment]
You mean while pressed and hold?

**Comment by teosarca** [comment]
yes, exactly... basically, we shall avoid the case when user sees a value, presses on the button and when then another value is set (because the value changed in meantime)

**Comment by damianprzygodzki** [comment]
i experienced that issue too. But imo, that problem will occur even with that freeze, because no one click and hold to ensure that the value is proper, and in case of some failure, slowly escaping from over the button.

it is just a timing issue, sometimes you have bad luck and press when value is changing - maybe we should slow down changing value on hover?

**Comment by cadavre** [comment]
I guess freeze on hover will do.

**Comment by teosarca** [comment]
yup, better!

**Comment by cadavre** [comment]
Hover + **focus**

**Comment by teosarca** [comment]
quick tested, but the value does not freeze when i am hovering the button.

**Comment by teosarca** [comment]
yes, pls.

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23255.md
