### ISSUE TITLE
Extend notifications functionality

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#288]
### Is this a bug or feature request?

Feature request

### What is the current behavior?

Notifications appear and disappear not taking into consideration user actions.

#### Which are the steps to reproduce?

Generate any UI error.

### What is the expected or desired behavior?

1. If mouse hovers notification – it shall not disappear until mouse is out.
2. Add running "progress bar" which will indicate how long notification will be displayed.
3. Stack similar errors into one notification. Thinking about adding "number pile" somewhere to indicate amount (as example look JS console).
4. Close API error into user-friendly (but lacking of info) short simple text reflecting HTTP errors. Show "Server error" (5xx), "User input error" (400), "Client error" (4xx) instead of full error texts.
5. Instead of full error text in notification add system flag (like "dev=true") which will enable error notification click to open modal popup with error details.

**Comment by cadavre** [comment]
Benchmark: http://codeseven.github.io/toastr/demo.html (enable "Progress" and play with mouse hover) – this is what we want.

**Comment by teosarca** [comment]
wow, very very nice!

about 4. and 5., i think backend shall provide this ( task #253 ). Until that, i think there is nothing u can do about it.

**Comment by cadavre** [comment]
@teosarca actually we can – we will simply always display this short texts in notifications. We very rarely have human-readable texts in errors and even if we understand "404something" or "field BPartner_ID is not NULL" – user doesn't have to. That's why I think this click on notification may help someone who actually would want to understand the error. Wdyt?

**Comment by metas-mk** [comment]
@cadavre Nice Idea, but let's discuss things like this later when we have time for such details. many to do before this ;-)

**Comment by cadavre** [comment]
@metas-mk disagree. It's a part of getting into #253 . We're lack of errors in many, many places so what we do right now is talk a lot about "what should happen" between frontend-API communication. Poor part is that we don't have user-friendly messages for users and we (devs) don't get errors that are saying what shall happen while calling API. In short: there's are no validators at all. What I'm trying to do is actually push you more into taking this issue into consideration, because as for me: it is "High priority" issue.

**Comment by metas-lc** [comment]
- If mouse hovers notification – it shall not disappear until mouse is out NOK
- Add running "progress bar" which will indicate how long notification will be displayed. NOK
(if i do an order and add an invalid bpartner it's OK (mouse hover and progress bar))
- Close API error into user-friendly (but lacking of info) short simple text reflecting HTTP errors. Show "Server error" (5xx), "User input error" (400), "Client error" (4xx) instead of full error texts. OK
- if you select show more you can see details about your error OK

about NOK:
- if you try to access a link with wrong ID, mouse hover works for about 6s, then the message disappears. If you hover and let go, the message disappears faster than the progress bar
e.g. https://w101.metasfresh.com:8443/window/143/aaaa

**Comment by metas-lc** [comment]
IT2
retested IT1 and all went fine
OK
