### ISSUE TITLE
Number Fields with digits precision missing digits in Layout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#29]
For example Products window Field PriceList, PriceStd. Should have digits (in current case at least 2, defined by currency precision).

**Comment by cadavre** [comment]
That was a subject to be discussed and implemented into API. @teosarca said you must discuss it internally and unify different numeric widget types (cause there are a few) and decide which work what way. We're waiting for this.

**Comment by teosarca** [comment]
IMHO,
* the backend shall provide the precision
* the backend shall provide the number strings, correctly formatted

About grid column's align, for fields like numbers we shall align them on the right.
I think we can introduce a new property on "element" layout:
`grid-align : left | right`

wdyt?

**Comment by cadavre** [comment]
We should add then to widget root:

* `precision` (0-n) to define number of digits after period
* `text-align` to define text alignment inside of widget

@teosarca how about providing us locale for user? We could make it in one shoot then while working on this.

Can you also list ALL numeric widgets and give live examples for them?

**Comment by teosarca** [comment]
Hi guys,

i was thinking about:

> precision (0-n) to define number of digits after period

and i am wondering why not having a decimal pattern instead of precision.
e.g.
* Integer: #0
* Number: #0.0###########
* Amount: #0.00##########
* Quantity: #0.############
* CostPrice: #0.00##########

or if this is hard to do in javascript, then i think we at least need to have:
* minimum-precision
* maximum-precision

wdyt?

**Comment by damianprzygodzki** [comment]
I think that API should return precision in number. Each user keystroke i have to validate input, so there is no place to parse this java decimal pattern because it is not working in JS.

Second case, whats the differences between minimum-precision and maximum precision? I think about validating precision as only avoiding case when user type too many numbers. If user type less then expected each place is 0.

**Comment by teosarca** [comment]
Fuck, i am puzzled. Let's go with one precision now and in meantime i have to think about it because this one smells like a big topic.

More, in future, @metas-mk  is thinking to have the precision dependent on selected currency, for those fields which are prices and amounts AND depends on document's currency.

**Comment by damianprzygodzki** [comment]
Okay :) But i think that currencies would be validated according to locales. For the moment, we can go with one precision 👍

**Comment by cadavre** [comment]
To summarize:
1) In JavaScript there is no Java digits formatting like `#0.00##########`.
2) Waiting to provide `locale` for user from API.
3) Please remember with https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString *we know* which currency should have what precision due to ISO 4217 standard. So basically if you're following ISOs we shouldn't even need precision for currencies.

**Comment by metas-mk** [comment]
Here we are not only deciding currency precisions but also pricing precisions, which are not standard. We have cases where currency precision could be 2 digits, but prices are defined with 3 digits.

**Comment by cadavre** [comment]
Roger! In this case "this one smells like a big topic".

**Comment by metas-mk** [comment]
As already posted in Skype Dev Channel by @teosarca :
"so, after turning the world upside down, couple of times, we decided that for the start we will have "one" precision (optional!), provided in layout->element
if the precision is provided, everything shall be rounded to that precision, everything shall be enfored to that precision
if the precision is NOT provided, everything shall be rounded AS-IS. in editing widgets we shall accept whatever number user enters."

**Comment by cadavre** [comment]
@teosarca

**Comment by teosarca** [comment]
shall be fixed in next rollout
see https://github.com/metasfresh/metasfresh-webui/commit/8bd9cfa5379c70cf6176858c3e77ed81798117e4
