### ISSUE TITLE
Process's "openViewId" is ignored when the process is called from single document

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#320]
Pls make sure opening single documents is respected too.
Pls consider refactoring this part to make sure that everybody is calling the same API for starting processes.

![image](https://cloud.githubusercontent.com/assets/1244701/23018050/4515719e-f445-11e6-85f6-113002e936bb.png)

**Comment by teosarca** [comment]
UPDATE, Might help, (fucking weird) after that test case, i've pressed ALT-left (back) and the HU editor suddenly popped.

**Comment by damianprzygodzki** [comment]
> Pls consider refactoring this part

There is no need to refactor that part. It is due to not well functionality planning at the beginning of work. From my pov there was a lack of use cases (in creating HU, enabling displaying document view in modal over other document view [not single document]).

>  to make sure that everybody is calling the same API for starting processes.
Everybody is calling the same API. There is no differences in calls.

**Comment by teosarca** [comment]
perfect, dziękuję.

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090

When calling the HU Receiving process the Modal HU  window is correctly opened. This happens when the process is called both from single and grid view.
