### ISSUE TITLE
The whole process parameters content vanished

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#333]
Case:
* open receipt schedules 
* call "Receive HUs" quick action
* see the screenshot: click on that field, try to pick that value
* the whole process panel was reset, content and title.

![image](https://cloud.githubusercontent.com/assets/1244701/23046824/909e149e-f4b4-11e6-81b3-2edfe7399574.png)

**Comment by damianprzygodzki** [comment]
Content dissapeared because this option wants to open modal with new empty document.
That is what i found in code '//TODO: Waiting for windowType from API for the new instance of entity'. So the functionality is doesn't work since implementing.

There is also no ability to open modal in modal.

What is the desired solution for You? What i can propose is:
- add ability to open multiple modals, connected to API, with documents (but i don't know that is good solution @cadavre form UX pov, to cover modals with another one.
- leave it as it is now (so here will be your help needed [we are waiting to return for lookups windowTypes of its entity]), and after clicking "New" option the user will be redirect inside of modal to create new entity and there will be need to open process again.
- for the option "New" in lookup opening the creating new entity in a new tab (there will be need to get this windowType from API too)
- or disable adding new entity in lookups inside modals

**Comment by teosarca** [comment]
I would go with "or disable adding new entity in lookups inside modals" for now.

**Comment by metas-mk** [comment]
Tested. Works nicely now. Does not show the new action when Packing material does not exist.
