### ISSUE TITLE
Wrong quickActions?selectedIds=0 call

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#349]
Test case:
* open any grid view
* select a record

![image](https://cloud.githubusercontent.com/assets/1244701/23077945/5725b4c4-f54f-11e6-9d85-33fd5fd17e22.png)

**Comment by metas-rc** [comment]
Results of IT 1: 

* Open Sales Order grid view, select a record (let's say it's 1003820)
* Select another record (let's say 1003805)
* Open Purchase Order grid view
* NOK: quickActions?selectedIds=1003805 ( same I selected before for Sales Order)
* Open Receipt Schedule grid view
* NOK: quickActions?selectedIds=1003805 ( same I selected before for Sales Order)

* It goes like this with all the other grid views i tried. The selected ID is the one I selected before.

**Comment by damianprzygodzki** [comment]
It has to wait for assumption #377

**Comment by metas-rc** [comment]
Please check our answer from https://github.com/metasfresh/metasfresh-webui-frontend/issues/377

**Comment by metas-rc** [comment]
Based on the comment in https://github.com/metasfresh/metasfresh-webui-frontend/issues/377

" No ID should be selected." But here, the last selected ID is still selected when moving to a new window. (See results of IT1)

Please, fix

**Comment by damianprzygodzki** [comment]
Cannot reproduce IT1

**Comment by metas-rc** [comment]
I tested again. Please, follow the steps I described: 
1. Go to purchase order, select one entry: 

![wrong id qa1](https://cloud.githubusercontent.com/assets/16001442/23462578/11bb8426-fe97-11e6-9a11-d26f29695802.png)


2. Go to home menu, and browse whole tree

![wrong id qa 2 browse whole tree](https://cloud.githubusercontent.com/assets/16001442/23462596/1d9f9bf6-fe97-11e6-909b-fb8ffe8a3b87.png)


3. Click on Sales Order => NOK: The old id from purchase order is still selected:

![wrong id qa3](https://cloud.githubusercontent.com/assets/16001442/23462611/2e23dc44-fe97-11e6-9d11-f056e81ca340.png)


4. If you press the 3 points there is an error because the same id is set! 

![wrong id qa4 press 3 points](https://cloud.githubusercontent.com/assets/16001442/23462621/3c1274b4-fe97-11e6-9888-405e7730850a.png)

**Comment by damianprzygodzki** [comment]
Checked, fixed, i believe it is good now.

**Comment by metas-rc** [comment]
I tested again on https://w101.metasfresh.com:8443

Until step 3 it's all fine. Selected ID is no longer wrong. But it is anyway preserved somehow, because when I click on references I get an error about it not being found.

Check the picture:
![image](https://cloud.githubusercontent.com/assets/16001442/23518410/09c2292e-ff7c-11e6-93da-1fcd2834e7a9.png)

**Comment by metas-lc** [comment]
IT
1. Go to purchase order, select one entry
2. Go to purchase order, select one entry
3. Click on Sales Order => OK, the purchase order isn't selected anymore
4. press the 3 points (actions menu) => ok, no errors, actions menu is there
5. select a sales order, open actions menu => ok, actions are there, no errors
