### ISSUE TITLE
Lines not "refreshed" after docaction reactivation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#352]
### Is this a bug or feature request?
BUG
### What is the current behavior?
When reactivating a document, the document line changes are not "refreshed"
#### Which are the steps to reproduce?
Reactivate a completed sales order which has packaging material line/s. Check the lines have not changed after reactivation. Press browser refresh after that. You will see that the packaging material lines disappear.
### What is the expected or desired behavior?
Refresh/ reload the lines after reactivation.
![image](https://cloud.githubusercontent.com/assets/13365687/23102564/8cc34f08-f6ab-11e6-9b2c-37da3ee76190.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23102565/9c2b738a-f6ab-11e6-83d5-a6aa61a0ad14.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23102568/9ffbf5fc-f6ab-11e6-9f76-b4dd79b0f4f9.png)

**Comment by teosarca** [comment]
NOTE: after "Re-Active", backend notified that the tabs "1" and "2" are stale.

![image](https://cloud.githubusercontent.com/assets/1244701/23102600/aa7d53dc-f6b4-11e6-80d4-3445c972fa23.png)

**Comment by teosarca** [comment]
backend change: when providing the changes, i've cleaned up documents which are from stale tabs (because that information might be collected before the tab was marked as stale),
but the problem persists...

But note, the issue happens only when the rows are disappearing (e.g. when we are reactivating an order and the second order line was removed).
It works OK when we complete an order and the second row was just created.


![image](https://cloud.githubusercontent.com/assets/1244701/23107991/aefb9982-f70e-11e6-8e57-b0df3bcb6b59.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23107996/d5324588-f70e-11e6-9689-90f7e1ec0182.png)

**Comment by damianprzygodzki** [comment]
Tested with case:

New order -> Add some product -> Complete order -> *packing is added as a new row* -> Re-activate order -> *packing is removed*

**Comment by metas-lc** [comment]
OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23352.md
