### ISSUE TITLE
frontend: View ID missing in "Create material receipt" opened from single view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#369]
See https://github.com/metasfresh/metasfresh-webui/issues/156

Remark that "Create material receipt" process is called with the underlying documentId instead of modal view's viewId and selection.

**Comment by metas-rc** [comment]
Results of IT 1

Tested on http://w101.metasfresh.com:8090/

Creating material receipt from single view still doesn't work.

Seson: The viewDocumentsID is the wrong one. It points to the receipt schedule instead of pointing to the selected HU.


The url was: 
http://w101.metasfresh.com:8090/window/540196/1000274

1000274 is the receipt schedule ID.

![bug in create material receipt](https://cloud.githubusercontent.com/assets/16001442/23254502/fc4390aa-f9c0-11e6-958a-16b23ab3cc38.png)

**Comment by metas-rc** [comment]
Results of IT2

Tested on http://w101.metasfresh.com:8090/

I repeated the tests. The material receipt is correctly created both when opened in grid view and in single view. Also, the view IDs are not broken any more. OK
