### ISSUE TITLE
Don't render unknown widget types but log in console

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#376]
reasons:
* it will allow us to introduce widget types ahead
* it's there is no use to have them there
* a WARN in console would be enough

For example: Price list, advance edit one of the rows, see the ProcessButton which is an unknown widget type (which will be implemented in one of the next issues).

![image](https://cloud.githubusercontent.com/assets/1244701/23144068/c2d0a79e-f7cd-11e6-83e0-c2b9d2551fd4.png)

**Comment by teosarca** [comment]
only if it's a quick fix

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090

I tested this before https://github.com/metasfresh/metasfresh-webui-frontend/issues/250 was integrated but I wasn't able to get to the advanced editing back then because of another bug. 
Any ways, I saw the log in console about the unimplemented widget type so I think this was solved.
