### ISSUE TITLE
"drop mode" has weirdly activated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#378]
Case
* open Receipt Candidates
* around where fields are, randomly click on the screen while dragging the mouse

The drop mode was activated but it shall not because we are not dropping something from outside or not even a file.

![image](https://cloud.githubusercontent.com/assets/1244701/23145657/9b86726c-f7d8-11e6-9a3f-75a6da55ed18.png)

**Comment by chmieludaniel** [comment]
I tried dragging something over a document, and the only thing that activated dropzone is MF logo. It actually is a file. We are unable to determine, if dragged object is something from outside of the browser. So what we can do is:

1) Remove any draggable items from document view. For now I found only logo. It can be done easily, by setting a logo as a background of some transparent element, instead of displaying the image itself. We can think of solutions for other draggable items, if you found such.

2) Filter files that are dragged, by their mime types. We should have a list of file types, accepted to be uploaded (either hardcoded, or provided by API).

**Comment by teosarca** [comment]
take a look at following case (see screenshot):
* open sales order
* select a part of the address text 
* drag it a bit
* the drop zone is displayed

=> NOK, but if it's not easily solvable, i think we can live with it.
But, what it's confusing for the user is, **how to get rid of it?**
I've clicked randomly inside and outside of the drop zone, clicked on Order Line and Order Tax tabs, pressed the action menu or the menu ... but the drop zone is still active.

![image](https://cloud.githubusercontent.com/assets/1244701/23177157/82305436-f86e-11e6-8139-b32ab1d5de89.png)

**Comment by chmieludaniel** [comment]
I pushed handling unsupported mime types. So when you drop text on it, the dropzone disappears and notification is displayed.

**Comment by damianprzygodzki** [comment]
Sorry guys, ive found an issue.

**Comment by metas-lc** [comment]
IT
1. open sales order
2. select a part of the address text
3. drag it a bit
=>  the drop zone is displayed, but as soon as you drop it, it disappears and notification is displayed
"Attachment
Dropped item [text/plain] could not be attached"
OK
