### ISSUE TITLE
Make the parameter names visible in filters

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#411]
### Type of issue

* Feature request (enhancement)

### Current behavior
* When a filter is opened, the longer names of parameters are nod completely displayed
### Expected behavior
* The whole names should be seen.
### Steps to reproduce
Please check the pic below:

![image](https://cloud.githubusercontent.com/assets/16001442/23258655/da22fa36-f9d1-11e6-8681-832c57d7f355.png)

**Comment by damianprzygodzki** [comment]
The filters have type **secondary** from the default, what means that the label and the input are sized with ratio 1:3. 

We cannot allow to auto-size labels in secondary input due to layout assumptions. 

Also we cannot fix the width of label to some length, because there is too much cases to fill them all.

What we can do here to display more is to provide from API type of widget like **primary** and then do not use fallback to **secondary** and achieve the 100% width label above the input. What it may cause is doubled height of filters dropdown.

**Comment by damianprzygodzki** [comment]
Do we have some new decision made here? Or can we close issue?

**Comment by teosarca** [comment]
Check with "primary" layout and it looks like this (see screenshot).
* for big filters, if u have to scroll, when trying to scroll the filter panel is closed => NOK
* the checkboxes does not look ok

@metas-mk  wdyt?

![image](https://cloud.githubusercontent.com/assets/1244701/25235441/ce2d2088-25ed-11e7-8ced-6f638dfe9989.png)

**Comment by metas-mk** [comment]
Let' try to get rid of the most big filters. We already started in material receipt to only have specialty filters where most of parms are already set as constants. If we manage to do that, I believe that we can go the path of primary layout BUT not for flags (looks horrible). WDYT?

**Comment by damianprzygodzki** [comment]
Than please just change it on API side to secondary for flags. So it is no more frontend issue, can we close it?

**Comment by teosarca** [comment]
Hi @damianprzygodzki 
I don't think so, because:
* the "type:primary|secondary" is considered for all filter parameters, and not for each one individually (see screenshot)
* more, personally, cannot imagine a place where a checkbox with type:primary which is actually layouted on 2 lines looks good => i think we might want to always layout the checkbox and label on same row.

![image](https://cloud.githubusercontent.com/assets/1244701/25268708/6d0c5d1a-2682-11e7-8a10-ecf839f5a159.png)

**Comment by damianprzygodzki** [comment]
@teosarca so change the type property to be inside the parameters - it is resposible for single widget.

we cannot differentiate and display one widget different than others. We wanted to make generic widgets and thats the way they are working, property 'type' is defining their design. It relay on API side.

**Comment by damianprzygodzki** [comment]
I think that frontend gives you now full ability to manipulate widgets layout in filters, so i am adding integrated flag instead of mf turn.

**Comment by teosarca** [comment]
pls fix the checkboxes layout.

**Comment by damianprzygodzki** [comment]
It is fixed, also with buttons, labels and switches. Isnt it working?

**Comment by teosarca** [comment]
didn't check it... thought it wasn't since i didn't see any commits since last talked.

moving it to testing then...

**Comment by damianprzygodzki** [comment]
Thank you

**Comment by metas-lc** [comment]
IT
to test it after this task is ready: https://github.com/metasfresh/metasfresh-webui-api/issues/334

**Comment by metas-lc** [comment]
IT
mainly it's fine, but the checkboxes are a bit too close and you can't see the whole text
![filter](https://cloud.githubusercontent.com/assets/16001666/25652664/0100eb30-2ff2-11e7-9c39-47ffcf4a46f2.png)

we would need a distance ...something like you can see in sales order for example (window/143/1005135)
![checkbox_order](https://cloud.githubusercontent.com/assets/16001666/25652797/95fd3e6e-2ff2-11e7-9f6d-221a05df3f6f.png)

**Comment by damianprzygodzki** [comment]
We are back again in the beginning. That's my solution.

> The filters have type secondary from the default, what means that the label and the input are sized with ratio 1:3.
> 
> We cannot allow to auto-size labels in secondary input due to layout assumptions.
> 
> Also we cannot fix the width of label to some length, because there is too much cases to fill them all.

Beside that, we have already implemented tooltip for labels, because the width of labels relay on width of your browser width.
![screen shot 2017-05-08 at 10 30 15](https://cloud.githubusercontent.com/assets/5701744/25796468/e52c3f40-33d9-11e7-8484-482c78c8cbe7.png)

What i can propose is to add additional styling type (side by side 'primary' and 'secondary') to allow change this ratio, or align the checkbox to the right, to keep consistency for all of that widget type.

**Comment by cadavre** [comment]
Due to our auto-generator of UI, we always keep label to input proportion 1:3 in secondary type inputs (this means also always for checkbox, switch and button widgets). Filter window uses same UI generator as document window – the difference is document window is simply wider – it gives it more space for label. Solution might also be making filter container wider but it won't solve other cases with ellipsis for checkboxes (like users with lower screen resolutions).

@metas-lc keep in mind we cannot adjust widgets per window because we use one, single and unified UI generator – making change in one place makes the changes in all of them. Please propose your solution in this perspective (look at @damianprzygodzki proposal above).

**Comment by teosarca** [comment]
as discussed, the backend shall provide (layout) type:"different type" (TBD) .

**Comment by teosarca** [comment]
Update: introduced "primaryLongLabels" layout type.
Will be available on next rollout.

![image](https://cloud.githubusercontent.com/assets/1244701/25886664/5cce1044-3567-11e7-83b0-b027b9d345b9.png)

**Comment by metas-lc** [comment]
IT
text in filters are visible. Checkboxes are far enough and on the same line. OK
other filters which are not checkboxes, have the text on separate rows OK
