### ISSUE TITLE
Fix hovering issue in the date range component

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#420]
### Type of issue

* Bug

### Current behavior

* When using a date range component ( a filter) the following happens: 
** The firstdate is selected => both the dateFrom and dateTo fields are set with this date : OK
** The second date is selected => both the dateFrom and dateTo fields are set with this date : NOK
** If you hover on other dates, the first date is also modified in the field: NOK
* This might be confusing from a user perspective 
### Expected behavior
* Since the first date was set, leave the date Field value as is .
### Steps to reproduce

Step 1: Selected first date as February 1:
![image](https://cloud.githubusercontent.com/assets/16001442/23294999/fdb3d5b0-fa76-11e6-97ff-6cbba054b03e.png)

Step 2: decided to set the second date on March 3:
![image](https://cloud.githubusercontent.com/assets/16001442/23295064/3fd65a12-fa77-11e6-88e6-9d6374666fdf.png)

Step 3: Clicked on March 3:

![image](https://cloud.githubusercontent.com/assets/16001442/23295122/98c1503c-fa77-11e6-955e-e20fffd61815.png)

Step 4: Move the cursor to March 10:
![image](https://cloud.githubusercontent.com/assets/16001442/23295198/ebee762c-fa77-11e6-9932-8b52a70954ea.png)

Step 5: Move the cursor out of the date component ( all back to normal):

![image](https://cloud.githubusercontent.com/assets/16001442/23295240/257dd61c-fa78-11e6-8e9c-b99ff03fb559.png)
 
Is this easy to fix? 
Please let us know about the complexity of fixing this.

**Comment by damianprzygodzki** [comment]
First, it is not easy to fix, it is a totally different behavior than that one.
Second, the current behavior is as every date range picker is doing, it is to selecting range, and do not chosing two dates separetely.

**Comment by cadavre** [comment]
This is how used library works: http://www.daterangepicker.com/

It's not perfect because it doesn't enable you to change once selected date on left and right sides of calendar. In fact this is not "input and calendar" + "input and calendar" but "input + input and calendar".

What I suggest to do is: enable `autoApply` – it will close picker after selection of 2nd date, and to change dates you'd need to open it one more time and select new range.

**OR**

Disable inputs for dates – this will leave only calendar to select from and to. But this will on the other hand disable possibility to see dates at once first next to other.

Both are not perfect but you can decide:
1. Leave as is
2. Use `autoApply` with clear on click.
3. Disable inputs.

I would say #2 will not confuse user.

**Comment by teosarca** [comment]
closing because it seems there is no solution for now.
