### ISSUE TITLE
Closing modal or window with unsaved changes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#453]
### Type of issue
Feature request

### Current behavior
The user can change data in a window or modal and juts leave the window via done or any navigation (URL change also breadcrumb navigation for example). In case the data is not enough to be saved, the data is lost.
In the case of modal overlay + done and subtab, the record is even shown after leaving, but not saved to the database.

### Expected behavior
If such case appears, then ask the user if she/ he really wants to leave the window with unsaved changes (browser functionality). Provide discard Endpoint for tidy up unsaved subtab data.

### Steps to reproduce
Open any window and new record w/ mandatory fields. Change something not mandatory. Leave the window w/o filling mandatory field.

**Comment by damianprzygodzki** [comment]
Is it ready from API side?

**Comment by teosarca** [comment]
Isn't this one?

![image](https://cloud.githubusercontent.com/assets/1244701/23555122/57dfdffc-0030-11e7-9137-acb8a1e0c662.png)

**Comment by teosarca** [comment]
Did a quick test:
* navigate to https://w101.metasfresh.com:8443/window/540196/wrong
* browser asks me if a want to leave the page => NOK, there is no point because i did nothing before so there is nothing to lose

suggestion: we somehow need to set the "onBeforeUnload" only if there is something to lose and as soon as the data is saved we shall reset the onBeforeUnload. wdyt?

**Comment by metas-lc** [comment]
IT 
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23453.md OK
