### ISSUE TITLE
If New document fails the window remains white

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#501]
### Type of issue
Bug / Feature request
### Current behavior
Open receipt new candidate.
The endpoint fails because it's not allowed.
But the page was already switched and the new page failed to load.

### Expected behavior
Stay it the window while the "/window/new" endpoint is executed and switch only if the it succeeded.

![image](https://cloud.githubusercontent.com/assets/1244701/23633059/e8391f48-02cc-11e7-87fa-2ea988f3b940.png)

**Comment by damianprzygodzki** [comment]
#253 Part of disscusion here about 404 generic error page.

**Comment by teosarca** [comment]
@damianprzygodzki  hmmm, ok, but how a 404 page would solve this case?

**Comment by cadavre** [comment]
Hmm, I believe this is the place for 404. ;) It is a bad behaviour to change user's URL without his action. If he click something – URL changes, what you want to do is change it back (history-1) and display error. We want to show 404 because it's default behaviour of web. Think about it also in cases where we don't have "previous pages" – like when entering page from copied URL.

**Comment by teosarca** [comment]
shall be solved as discussed on https://github.com/metasfresh/metasfresh-webui-frontend/issues/651

**Comment by damianprzygodzki** [comment]
Closing it due to integration of #651
