### ISSUE TITLE
string fields are not marked as mandatory when empty

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#548]
### Type of issue
Bug
### Current behavior
string fields (e.g. Name) are not marked as mandatory when you remove them 
### Expected behavior
field should get red and marked as mandatory
### Steps to reproduce
1. go to Product window
2. take an already existing product and remove the name
=> product is saved, even if the name is mandatory. 
=> no red mark to see that the name is not set
=> name is empty not null, probably that's why

**Window:** 140

**Entity:** e.g. 1000001

![productname1](https://cloud.githubusercontent.com/assets/16001666/24039544/4b57b9ce-0b0e-11e7-8948-c1feb66e4cd0.png)

![productname2](https://cloud.githubusercontent.com/assets/16001666/24039546/4cf803d8-0b0e-11e7-8116-be0dddda1ddf.png)

**Comment by teosarca** [comment]
hmmm, i think this one can and shall be completely solved on backend: https://github.com/metasfresh/metasfresh/issues/1173

**Comment by teosarca** [comment]
update: we workaround this issue on backend side,
but i think that we shall also implement this logic on frontend. 

i.e. for text fields, null **and empty** shall be considered as "field is not field"... so in case it's mandatory, it will be painted accordingly.
@damianprzygodzki  can we implement this easily on frontend, without turning the world upside down and without workarounds ?

**Comment by damianprzygodzki** [comment]
We are marking mandatory field in that way (and it is okay, because it happens fully on frontend) but in my opinion we should do not force `input-error` state on frontend site. I can copy the same condition that triggering `input-mandatory` state, but i fear that forcing something on frontend, that relays on API in future can corrupt API state. I.e. you would set on API that input is valid (just because) and some condition will be blocking API state - and without  going into code, you cant check why.

**Comment by cadavre** [comment]
True validation shall be made on backend because it's the place to save correct data. Front-end is responsible for displaying validation results, not validation itself. We should stick to one place with validation and not spread it because it will end up not being debuggable.

**Comment by teosarca** [comment]
Thanks guys for checking it.
Seems ok now so i am closing this issue.
