### ISSUE TITLE
Sorting changed after selection and navigation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#61]
Szenario: open window/143 Sales Order grid view
- Sort by DocumentNo. (asc or desc)
- go to page 5 for example
- select an order with doubleclick
- open the navigation in breadcrumb for window/143 Sales Order grid view again
  --> you are still on page 5 BUT the sorting is broken. Youmostly don't see the previously selected order anymore.
  --> wish: if you go back to overview grid, then open the overview with previous row selected and soting same as initially.

**Comment by cadavre** [comment]
I'd say if someone opens element from a Menu navigation he should see default page – it always works like this. But on the other hand it *must* open same list, sorting and filtering when pressing "Back" in browser page so I keep this Issue open. It is one yet-to-be-discussed topics because we were thinking about this few days ago in other case: user should be able to share a URL to gridview with predefined: page, sorting and filters. We must in this case think about how to generate URL for such cases. This will also solve above problem with "Back".

@teosarca how long do you save viewId for gridview?

**Comment by teosarca** [comment]
@cadavre  atm it's hardcoded to 1hour after last access.
