### ISSUE TITLE
Address editor silently ignores changes if the mandatory fields are not filled

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#619]
### Type of issue
Bug

### Current behavior
NOTE: in address editor, the country field is mandatory

When editing a new address, if you fill the other fields (e.g. address1) but not the country and then you click away, the frontend is silently ignoring the changes (i.e. does not call the /complete endpoint)

NOTE:
* backend informed that country is mandatory
* backend filled correctly the saveStatus/validStatus

NOTE2: please also check/fix this issue on Product Attributes editor.

### Expected behavior
IMHO, in this case, the frontend shall ask user if he/she really wants to cancel editing in this case.

### Steps to reproduce
* pick a BPartner, e.g. https://w101.metasfresh.com:8443/window/123/2156482
* try to add a new BP location
* click on location editor
* fill the Address1 field, but DO NOT fill the Country field
* click away
=> frontend is silently ignoring the changes, without any question => NOK

**Comment by damianprzygodzki** [comment]
I can't understand that. The mandatory property was introduced to avoid saving entity without filled value. It is not "silently" ignored, but vividly parsed:
```
//there are required values that are not set. just close
        if (mandatory.length && !valid){
            return this.handleToggle(false);
        }
```

It was introduced by the issue #294 when leaving attributes widget was returning error, due to not filling mandatory fields.

The patch for other fields in attributes are not canceled by mandatory field, is regularly patched. 

If You want to remove that validation, so what is reason of mandatory field there? Only visual? And it will be properly parsed by API? So should we keep that consistancy everywhere? And remove mandatory validation for every widget?

**Comment by cadavre** [comment]
It's another case of "we started editing and didn't finished with all required fields". Due to recent changes of adding "Do you want to leave?" we should add something similar to this also for attributes widget.

**Comment by damianprzygodzki** [comment]
Yes, no problem - but, i think that we still do not call `complete`.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* "Do you want to leave?" when leaving the address edit after setting PLZ, but without setting country: OK

@teosarca: i did not get any question when leaving the product attributes editor, e.g. in orderline, is that OK? afiar there are no mandatory fields anymore in product attributes editor?

**Comment by damianprzygodzki** [comment]
@teosarca It is the same widget, so there is no difference. Could you locate ASI with mandatory field?

**Comment by metas-dh** [comment]
Results of IT2
tested on w101

* set one tye of ASI as mandatory for testing purposes
* "Do you want to leave?" when leaving the attribute editor after setting attributes, but without setting the mandatory one: OK
