### ISSUE TITLE
Shortcuts behavior sometimes weird

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#641]
### Type of issue
Bug
### Current behavior
Sometimes when toggling through the menues, it happens that the shortcut for a menu needs 2 presses to open the menu. It has then close of old menu in 1st step, and open the menu in 2nd.
### Expected behavior
Shall always work with 1 press/ step.
### Steps to reproduce
Try the following in Sales Order window /window/143/1005041
ctrl+1 OK
ctrl+5 OK
ctrl+3 OK
ctrl+1 OK
ctrl+5 NOK (have to press twice, 1st one closes menu1, 2nd one opens menu5)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
sales order window, tried ctrl+1,2,3,4,5 and 6 in multiple orders, including 1,5,3,1,5 and they work fine, opening the menus directly, without having to press twice. OK

question: 
when i press ctrl+1,2 and 3 twice, the menu opens and closes
but when i press ctrl+4,5 and 6 twice, the menu just refreshes, does not close. Is that OK?

i'll create a new task for my question and close this one since it's ok

**Comment by damianprzygodzki** [comment]
@metas-lc Please, do not open another issue. It is bug followed by this one. Im gonna do quickfix.

**Comment by metas-lc** [comment]
@damianprzygodzki ok, thank you

**Comment by damianprzygodzki** [comment]
Done

**Comment by metas-lc** [comment]
IT2
retested the testcase above. Works fine
