### ISSUE TITLE
Creating a new Discount record error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#644]
### Type of issue
Bug
### Current behavior
Open window 233 (Rabatte). Press breadcrumb Rabatte Grid View. Popup "do you really want to leave?", Yes. Press action menu "New". Error.
### Expected behavior
Shall not have the error.
![image](https://cloud.githubusercontent.com/assets/13365687/25049318/9e14f0ac-2141-11e7-89f7-f6bd91c53d70.png)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
1. open Discount Schema window
2. create a new one, set all mandatory fields
=> document is not saved because validTo is not set (the field is not there)
3. press breadcrumb discount grid view
=> asks me if i want to leave
4. press ok
=> no entries are shown (ok in my case since i don't have any saved)
5. go to action menu, select New
=> details view to create a new entry opens without errors OK
