### ISSUE TITLE
Show lookup errors in lookup

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#650]
We want all lookup-related errors to be displayed in lookup like this:

<img width="595" alt="zrzut ekranu 2017-04-19 o 12 46 43" src="https://cloud.githubusercontent.com/assets/461796/25176393/48069c18-24fe-11e7-9462-434a713f3424.png">

To achieve this we need to get `400 Bad Request` in API responses so we can know that this particular errors are meant for user. Other errors like `500 Server Errors` shall be displayed as now – in notifications.

`400 Bad Request` error messages MUST be short to display in single-line.

**Comment by teosarca** [comment]
basically, atm we are returning 404 not found if there was no result for given lookup query string.

All the other errors should not happen... i mean, they are exceptional and usually are because of some database failures. And in that case i cannot distinguish which shall be 400 and which shall be 500.

**Comment by cadavre** [comment]
I can see that 404 is properly show inside of lookup. Only errors like "No price system" or "Missing BPartner location" are displayed in notifications which is fine for me.

If it's fine also for you – we can close this issue once for all.

**Comment by teosarca** [comment]
yup, let's close it because don't know how to handle it now...
