### ISSUE TITLE
Use Key in long drop down list

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#738]
### Type of issue
Feature request

### Current behavior

![image](https://cloud.githubusercontent.com/assets/16079655/26012817/1c743744-3756-11e7-87c5-0c89d78c6560.png)

### Expected behavior
if I press S I would like the cursor to jump to "Standard" to spare using the mouse on every product I create.

### Steps to reproduce
1. go to product
1. create new
1. click into product category
1. press key S
1. NOK: nothing happens

**Comment by metas-lc** [comment]
IT
tested the steps above

1. go to product
2. create new
3. click into product category
4. press key S
=> it sends you to category that starts with S OK
5. press a 
=> nothing happens because there is no category starting with A OK
6. press Z
=>  it sends you to category that starts with Z OK
6. press C
=>  it sends you to category that starts with C OK
