### ISSUE TITLE
Show included view's filters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#741]
### Type of issue
Feature request

### Current behavior
Manufacturing order => Issue/Receipt => select an "CO"mponent line => Issue HUs

The filters for the included view are not rendered.

### Expected behavior
They shall be rendered like this:

![image](https://cloud.githubusercontent.com/assets/1244701/26025851/29590af4-37f9-11e7-8ea9-6b62b989af24.png)

Required for: https://github.com/metasfresh/metasfresh-webui-api/issues/364

**Comment by damianprzygodzki** [comment]
This case was discussed, and there weren't any infos about using filters in includedView. Even more, i've disabled it, because the white bar (with quickactions) is for `Order Issue/Receipt`, not for includedView, and switching scope of quickactions is just a overwriting quickactions of `Order Issue/Receipt`.

There is no ability to display filters like that:

![image](https://cloud.githubusercontent.com/assets/1244701/26025851/29590af4-37f9-11e7-8ea9-6b62b989af24.png)

Because:
![untitled](https://cloud.githubusercontent.com/assets/5701744/26093469/5be8a74e-3a16-11e7-91f9-d6bff917b0b4.png)

The filters are rendered normally, but in own regular component (that part is hidden due to do not have doubled controlls).

![screen shot 2017-05-16 at 09 05 14](https://cloud.githubusercontent.com/assets/5701744/26093577/ca77c62c-3a16-11e7-8c1f-94d0b97be1b9.png)

One solution i see is to replace filters of parent (as quick actions) but in my opinion it will be misleading, the filters would be rendered on the beginning of that container, right next left border.

**Comment by cadavre** [comment]
I'm thinking about if users will actually use this filters? It pops out when issuing a product and needs to accept a single selection. After selection is done this filter will eventually close and while reopening – new filters would need to appear and be set one more time. I think using filters here would take as much time to find an element than simply looking for it. Let's make UI elements that actually help users. :) If I'm wrong in my assumptions – I'm open for use-cases. :)

**Comment by damianprzygodzki** [comment]
- display filters and quick actions for both views
- display pagination not nested
- hide left filters and quickaction when the included view is open

**Comment by cadavre** [comment]
About alpha overlay – it's already applied for parent "table" and it should stay this way.

**Comment by teosarca** [comment]
yes, that's correct.

**Comment by teosarca** [comment]
quickly checked this feature on local: pls remove that bottom gap

![image](https://cloud.githubusercontent.com/assets/1244701/26197849/765d45a0-3bcc-11e7-9805-3a254ff3d57f.png)

**Comment by metas-lc** [comment]
IT
1. Manufacturing order -> Issue/Receipt -> select an "CO"mponent line -> Issue HUs
=> The filters for the included view are rendered OK
