### ISSUE TITLE
Date widget behaves weird when using keyboard

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#75]
Test case:
- take any Date field
- try to edit it using keyboard, e.g. try typing 25.10.2016
- NOK => you cannot, behaves very weird

![image](https://cloud.githubusercontent.com/assets/1244701/19758495/021629c2-9c31-11e6-89ee-accd7d0c7c95.png)

**Comment by cadavre** [comment]
What browser and system?

**Comment by teosarca** [comment]
Hi @cadavre ,

I am using chrome on win7.

Just try typing a date in the date box (e.g. try typing some thing like 07.02.2016) and let me know if u succeed :)

**Comment by cadavre** [comment]
Correct. Date cannot be changed due to onChange event. :) I was testing it on some other field and it was working. @damianprzygodzki can you elaborate what can we do here? Eventually lock keyboard edition.

**Comment by damianprzygodzki** [comment]
Okay, i researched that - and there are two ways of escape from that problem.

Problem is that this input is controlled - that means, each date change runs update of state and injecting it inside input. When we are choosing date from dropdown, datepicker returns parsed Date object. When we are choosing it by keyboard, then we need to get the value by ourself.

So when we want to get date from picker and pass it by keyboard there is problem, because input is validating itself each change - it looks like smth is weird with input, but check this, it is only parsing to date format. And when we want to handle it by ourself - take the date and do not pass it each time to validation, there we cant use picker.

So the best solution for me is block edition "by-hand" of that fields.

**Comment by teosarca** [comment]
Hi guys,

User keyboard input is one of the most important features for us, in terms on usability.

**Comment by damianprzygodzki** [comment]
After really deep research and contacting author of that plugin, the only solution i see is to

1) change the plugin ( there is no warranty that other can do that work better )
2) use native date input ( no support in every browser & lack of own design )

**Comment by cadavre** [comment]
Maybe one of this:
1) Disable "dd.mm.yyyy" date edition in input, but intercept keyboard usage on datepicker and use arrows to change days/month inside of picker itself. If this is possible.
2) Fork picker repo and do necessary changes.

**Comment by damianprzygodzki** [comment]
Ad 1) It is not posibble. If i would have access to inside of that component, i will overwrite onFocus, onBlur, onChange events and get rid of our issues.

Ad 2) We can, but it may cost time.

**Comment by damianprzygodzki** [comment]
https://github.com/YouCanBookMe/react-datetime/pull/164

I am waiting for that PR. Maybe it will solve our problems.
