### ISSUE TITLE
Select-all-filtered option in general

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#752]
### Type of issue
Feature request
### Current behavior
Currently, only a select all on this page link exists on the bottom of grid view pages.
### Expected behavior
When pressing on 
a) "select all on this page", all record of the page are selected and the amount of selected record are showing above the link (e.g. "25 items selected").  As soon this happens the previous link shall change to "Select all xxxx records", but **only** if we have more then one page. This shall be possible so the user can select then and use the selected for the quick actions. Provide an additional "clear selection" functionality next to the selected amounts.
b) As soon as the user presses on that link, the link shall disappear and only the amount hint "xxx items selected" is shown and the additional "clear selection" functionality.

![image](https://cloud.githubusercontent.com/assets/13365687/26126193/fb0e5292-3a84-11e7-992a-e618cd0da86d.png)

**Comment by teosarca** [comment]
Suggestion:
In case user selected all on all pages, we need to send this information somehow.
I would suggest that in all places where we are sending the selected documentIds array to send something like
```
"viewDocumentIds" : [ "all" ]
```

**Comment by teosarca** [comment]
Update: i've started implementing the backend support for this task: https://github.com/metasfresh/metasfresh-webui-api/issues/388.

**Important:**
* in case user selected ALL on all pages, the frontend shall send to backend:
** in case it needs to send an array of selected document Ids: "viewDocumentIds" : [ "all" ]
** in case it needs to send a comma separated string of documentIds: "all" 

* **never ever send the "all" keyword in case there is only one page**. Some backend processes rely on that.

**Comment by metas-lc** [comment]
IT
1. open a window which has multiple pages (e.g. sales order)
=> No items selected
Select all on this page
2. press on "Select all on this page"
=> 20 items selected
Select all 1686 items
3. press on "Select all 1686 items"
=> 1686 items selected
Select all on this page
4. select a line
=> 1 items selected
Select all on this page
.
1. open a window which has only 1 page of data (e.g. Price System)
=> No items selected
Select all on this page
2. press on "Select all on this page"
=> 11 items selected
Select all on this page
3. select a line
=> 1 items selected
Select all on this page

note: clear selection is not needed since we can deselect the rows by selecting only 1
