### ISSUE TITLE
Empty Filter vs. Default Value in Window Filtering

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#762]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
When using Window Filters, then the initial behavior is that Flags are considered as null/ not set. As soon as you click a Flag filter then results are Filtered by FlagValue = 'Y'. When clicking off, everything is filtered by FlagValue = 'N' and the user has no single possibility to reset to null to not consider anymore.
#### Which are the steps to reproduce?
Try Filtering in Product Price Window.
### What is the expected or desired behavior?
Similar to ID Fields one should be able to switch off/ nullify the filter with some kind of 'X' (x in a circle) to empty the filtering criteria without resetting the whole window filter.

Thread started in other repo, please check discussion here first: [https://github.com/metasfresh/metasfresh-webui-api/issues/143](https://github.com/metasfresh/metasfresh-webui-api/issues/143)

![image](https://cloud.githubusercontent.com/assets/13365687/23094574/d81b5c80-f5fb-11e6-93e1-ab04be9b7649.png)

**Comment by cadavre** [comment]
So right now we have:
Checked – Yes
Not checked – No
and no possibility to set "don't filter by this field", right?

**Comment by teosarca** [comment]
@cadavre  true

**Comment by cadavre** [comment]
TODO @cadavre – mock-up filtering for Yes/No (+clear).

**Comment by cadavre** [comment]
My proposition #1 to keep checkboxes is to introduce new state. Also change circle 'x' into simple text link which clears the filters (and id 100% obvious to user that THIS filter is active and can be cleared).
<img width="452" alt="zrzut ekranu 2017-05-23 o 16 33 56" src="https://cloud.githubusercontent.com/assets/461796/26359484/e627df6e-3fd5-11e7-98f3-ea2710d1eded.png">

This basically adds new state with green, double-weight border which means "filtering with 'No' value". Eventually we could add title="" attribute to show system tooltip to explain.

**Comment by metas-mk** [comment]
@cadavre very nice solution. I like it. That would also then affect the main view and then shown as "Filtered with no" if the content of the flag is "N", right?

**Comment by cadavre** [comment]
In main view I would leave states as they are now, because of two reasons:
1. It would simply look strange in document view when checkbox would glow with green with no purpose. (Remember that main idle state color in UI is this grayish blue like in "Not filtered by".)
2. Yes/No for user is now (and always for checkbox!) indicated with "tick" inside of checkbox – it is actually responsible for making value 1 or 0 for this field. Different border color, on the other hand, means in metasfresh UI that particular field has some different state (like "is mandatory" or "is not valid") – I'd love to stick to that unified assumption.

To clear the doubts – no, I don't think "No" and "Not filtered by" would be mismatched by users – especially when there is "(clear)" which also pretty clearly indicated that filter is "on".

**Comment by metas-lc** [comment]
IT

1. Open Bill Candidates
2. go to filter, select default and select a checkbox multiple times
=> notice it has 3 states: Y (with x), N (with x) and Empty (without x), the last one means is neither Y or N
=> default state is Empty without x OK
OK
3. set Komplett Abgerechnet eff on Y, apply
=> invoice candidates are filtered for complete eff OK
4. go back to filters
=> notice that all checkboxes have x. NOK because it gets you confused that is N instead of empty
5. press apply 
=> same results (even if they have x they have the empty value)

6. Testcase for "visibility" that after you open the filter again, the ones with x are in fact empty:
- filter for: Auftrag 0863, Freigabe zur Fakturierung Y, Komplett Abgerechnet eff. Y
=> you have 2 results
- clear filter, and filter for Auftrag 0863, Komplett Abgerechnet eff. Y
=> 2 results
- open the filter again - notice that Freigabe zur Fakturierung is N (don't change), apply
=> 2 results
- open the filter again, set Freigabe zur Fakturierung to N, apply
=> no results


pics for opening the filter again:

![filters1](https://cloud.githubusercontent.com/assets/16001666/26366424/be184414-3ff3-11e7-814b-f105d2a23425.png)

![filter2](https://cloud.githubusercontent.com/assets/16001666/26366430/c27f8c60-3ff3-11e7-87d2-96e1f2b6e222.png)

**Comment by metas-lc** [comment]
IT
retested: works fine.
- checkbox is on Y -> fill with green and "(clear)" right near
- checkbox is on N -> green margin and "(clear)" right near
- checkbox is empty -> grey, "(clear)" is hidden
- if you press on clear the button becomes grey and it hides
OK
