### ISSUE TITLE
Honor tab stale flag also when editing in advanced mode

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#769]
### Type of issue
Bug
### Current behavior
While editing/patching a document, as a response we can also stale some of the included tabs.
When editing in advanced mode, this property is not considered => NOK
When editing in normal mode, everything works ok.

### Expected behavior
stale tabs property shall always be honored.

### Steps to reproduce
Atm, i can do it only in development, but in future this would happen when you tick/untick the Active flag.

![image](https://cloud.githubusercontent.com/assets/1244701/26278911/4cebb696-3dae-11e7-9a00-47bba48ccbfe.png)

**Comment by damianprzygodzki** [comment]
Yeah, it was implemented already, but i see that it was flagged as a bug, and you wanted to disable the updates of tabs when modals are edited (#704). Should we revert it? Maybe would you mind to create a list of accepted cases of loading includedTabsInfo, and then we could be able to create condition for that.

**Comment by teosarca** [comment]
Hi @damianprzygodzki ,

Ideally would be to flag the tab(s) as stale.
As soon as user gets out of advanced edit, the frontend shall refresh the tabs which were marked as stale.

About https://github.com/metasfresh/metasfresh-webui-frontend/issues/704 ,
i wasn't aware that those tabs were refreshed because one of the previous endpoint response marked them as stale.
If that's the case, pls always honor the "stable" request.

So for now, let's do it as described and if it's a quick win, also pls implement the "ideally" case.

wdyt?

**Comment by damianprzygodzki** [comment]
Sorry, i can't understand the solution. Let me clarify.

We have two ways of updating the tabs:
1) When response from PATCH comes, we are updating tabs that are in `includedTabsInfo` property.
2) When information about queryOnActive in layout of window (that is a constant for time of window component life) and tab was activated.

> Ideally would be to flag the tab(s) as stale.
We have no way to flag it tab as stale (`includedTabsInfo` brings updates, `queryOnActivate` is defined in layout)
> As soon as user gets out of advanced edit, the frontend shall refresh the tabs which were marked as stale.
Advanced edit basically has no event on closing itself, because it is just a regular window. We can add it and refresh 'stale tabs' (i am thinking these ones with property `queryOnActivate` set in layout already), but would it be only when the `advancedEdit` flag is set? Will it be there some other cases to refresh tabs on modal closing?
> If that's the case, pls always honor the "stable" request.
What is 'stable' request?

**Comment by teosarca** [comment]
> What is 'stable' request?

ahh sorry, typo, let's me rephrase it: in case frontend gets stale:true for a given tab it shall always be honored.

**Comment by damianprzygodzki** [comment]
So, correct me if i am wrong, the solution here is:
- revert #704 and always fetch tabs from includedTabsInfo
- when the button `Done` is pressed and `advancedEdit==true` we should fetch tabs with `stale:true` property

**Comment by damianprzygodzki** [comment]
As discussed on skype:
- if patch is in modal, fetch `stale:true` tabs on modal closing
- if not leave it as it is now (fetch `staled` tabs after patch response)

**Comment by metas-lc** [comment]
IT
1. go in a window which has multiple included tabs (e.g. Product 140)
2. go to advance edit and change something there (e.g. is Active)
=> in inspect, notice that the tabs were not fetched OK
3. press on done
=> in inspect see that tabs are fetched (7 in my case) OK
