### ISSUE TITLE
Advanced Edit w/ key [ctrl]+e too many [tab] for scroll

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#789]
### Type of issue
Feature request
### Current behavior
When opening the Advanced Edit Window, it takes too many [tab] until the user is able to scroll with arrows or page-down/up.
### Expected behavior
Open the advanced edit and allow the scroll to be possible directly.
### Steps to reproduce
Open Sales Order window window/143/
Press [ctrl]+e. Try to scroll w/ page-down after opening (does not work). Now press [tab] 4 times. Then you are able to scroll.

**Comment by metas-mk** [comment]
Info: same happens w/ opening the Advanced edit w/ the mouse but only takes [tab] 3 times then.

**Comment by damianprzygodzki** [comment]
The problem is that we assumed to be focused on first field in window after opening. I've tested that and after `ctrl+e` the advanced edit modal is opening and focus is on first input - the arrows for scrollin shouldn't be there supported. The page down working okay, you can scroll with `page-down/up` even focused on field - default behavior kept.

**Comment by damianprzygodzki** [comment]
Okay, now i find out, the filled lookup is shaking off the focus of itself.

**Comment by damianprzygodzki** [comment]
To achieve this functionality i've changed behavior of focusing in modals.

The case was that lookup when filled is not autoFocusing itself so it was loosing its focus.

**Comment by metas-mk** [comment]
@damianprzygodzki 
As discussed in our talk. Currently, it happens that the focus is not set onto the first field anymore when creating "new". Take window/143/ for example. It's highly important for the user to press "new" (keyboard or mouse) and then directly start writing in the first field w/o the need to press tab.

**Comment by damianprzygodzki** [comment]
The problem here is, when we are focused inside lookup (doesnt matter where) the page-down and page-up scrolling is disabled.

So to clarify:
- if we are in `MasterWindow` (/window/143/{someId}) we should be focused initially in first field
- if we are in `Modal` (i.e. Advanced Edit, Process with parameters, etc...) the focus should be on first `section` (that part that is wrapping element lines) to be able to scroll by the `page-down/up`

**Comment by metas-mk** [comment]
Perfect. Thx.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
