### ISSUE TITLE
Bookmark a window/process/report and show in Quick Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#803]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the "Quick Menu" opened via Navigation Menu, shows a static selection of Menu entries.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
The User shall have the possibility to "star" a window. This could be done in Action menu where the Window Name (UI Element Name) is added as Header or the left action menu and an additional "star" Toggle button (light gray when not set, metasfresh green when set). If the window is starred this way, then this Window is shown in Navigation menu w/ its Menu Tree Structure and possibly other Windows (like New ...). Additionally, the star is shown in those elements in Sitemap Tree too (pale metasfresh green star when set, when hovering with the mouse or selecting w/ keys then metasfresh bright green star. When not set don't show the star, only when hovering show a light gray star that the user can toggle via mouse there too.)

@cadavre wdyt?

![image](https://cloud.githubusercontent.com/assets/13365687/26527093/af81381a-438c-11e7-9437-cb5654611641.png)

![image](https://cloud.githubusercontent.com/assets/13365687/26527139/c9fb9856-438d-11e7-92bc-aa05fa3934d7.png)

**Comment by cadavre** [comment]
Assigned graphic designer for work tomorrow – will provide exemplary design.

**Comment by teosarca** [comment]
NOTE: this is more a concept task. We are and we will split off particular tasks from it.

**Comment by cadavre** [comment]
@teosarca are you going to prepare some new endpoints for this or we will be using menu endpoints? I'm asking mainly because according to feature request description we will have possibilities:

* to star `window`
* to star `group`
* to star `process`
* to star `report`

According to each above type – how will we get data to render particular bookmarks in Actions menu? This question is 150% important in case of group.

**Comment by teosarca** [comment]
@cadavre  loud thinking:
* to star a window/group/process/report/etc we shall have only one endpoint, something like: "POST /rest/api/menu/node" { "favorite" : true|false }.
* the favorite flag shall be provided for each menu node when calling any of /rest/api/menu/... endpoints which return menu nodes.

wdyt?

**Comment by cadavre** [comment]
+1, but missing answer for filling Actions Menu.

> If the window is starrred this way, then active then this Window is shown in Action menu

![zrzut_ekranu_2017-05-31_o_12_22_50](https://cloud.githubusercontent.com/assets/461796/26627862/3581d886-45fc-11e7-9441-32a7930dc010.jpg)

So it's shown here @metas-mk ?

**Comment by cadavre** [comment]
As discussed: Frontend is modifying actions menu (adding header with starring) and sitemap (adding starring). Filling navigation menu with regular menu and/or only bookmarks is due to backend.

1. We can assume that backend will strip number of elements returned for Navigation menu wth bookmarks. Users will be able to add as many bookmarks as they want though. We can wait for any feedback from user about this though. Backend will restric to a maximal possible qty of quickactions for the start.
2. We can assume that in case of no bookmarks backend will send regular menu as it is now. Would solve „first prototype” issue.

**Comment by teosarca** [comment]
API provided here: https://github.com/metasfresh/metasfresh-webui-api/issues/425

**Comment by cadavre** [comment]
Designs for bookmarking in Actions menu with window name header:
![bookmark-1-actions](https://cloud.githubusercontent.com/assets/461796/26668073/59fc4bc2-46a8-11e7-8005-93ffde773cea.png)
![bookmark-1-actions-on png](https://cloud.githubusercontent.com/assets/461796/26668075/5bf38f62-46a8-11e7-949b-85ef4363fced.png)

Sitemap:
![bookmark-sitemap](https://cloud.githubusercontent.com/assets/461796/26668079/617df3aa-46a8-11e7-8ab2-12fa03e70a11.png)

Navigation menu is not affected anyhow and, as discussed, backend is handling if favourites are displayed instead of regular menu. Also discussed: if any favourite is set – display navigation menu with favourites ONLY and if no favourites are set – display regular menu as it is now.

**Comment by damianprzygodzki** [comment]
Is it accepted, ready for development?

**Comment by metas-mk** [comment]
@damianprzygodzki @cadavre 

> Is it accepted, ready for development?

agree. thx.

**Comment by cadavre** [comment]
About navigation menu (while displaying bookmarks already): shall it display stars same as in sitemap?

**Comment by teosarca** [comment]
good point... let's talk about this in our today's meeting.

**Comment by cadavre** [comment]
Additional:

* Deprecated "GET /rest/api/menu/node". Please use "GET /rest/api/menu/node/{nodeId}"
* Deprecated "GET /rest/api/menu/path". Please use "GET /rest/api/menu/node/{nodeId}/path".

^ Are those to implement?

**Comment by teosarca** [comment]
> About navigation menu (while displaying bookmarks already): shall it display stars same as in sitemap?

I would say no because usually there you will get only the "bookmarked/starred menu entries".
But pls mind how the frontend shall call the [GET /rest/api/menu/root](http://w101.metasfresh.com:8081/swagger-ui.html#!/menu-rest-controller/getRootUsingGET) endpoint.
i.e. 
* in case of navigation menu, the endpoint shall be called with "favorites=true" parameter
* in case of sitemap menu, the endpoint shall be called without favorites parameter (or favorites=false).

**Comment by teosarca** [comment]
> ^ Are those to implement?

Yes. Please always check the swagger documentation, i.e. http://w101.metasfresh.com:8081/swagger-ui.html#/menu-rest-controller

While swagger it's far from being perfect it's the most accurate and up2date documentation.
There you shall remark the deprecated endpoints (those which are striked). 
The deprecated endpoints shall not be used and are to be deleted in nearest future.

**Comment by teosarca** [comment]
Hi guys,

quick checked it seems we have a missing requirement: we shall also be able to start/unstar menu groups.
e.g.
![image](https://user-images.githubusercontent.com/1244701/27032666-ac7b3032-4f7e-11e7-961c-4bef5a468250.png)

**Comment by teosarca** [comment]
Update: decided with Mark to not have that requirement. More info will follow.

**Comment by metas-mk** [comment]
Tested. Works nicely in Sitemap and Window Headers. Switching on/ off is fine. Please provide these additional changes:

a) Don't show the Notification that a bookmark is added. Just switch on/ off. The user see's it as a green star if it's switched on or gray/ empty if it's not bookmarked.

![image](https://user-images.githubusercontent.com/13365687/27041828-68a9170e-4f95-11e7-8344-1cd6eb3b6e5f.png)

b) The Layout of the navigation menu does not look nice. I Would propose to fill the left Side of Navigation first and then the right one, and not try to "balance" the length on each side. @cadavre WDYT?
![image](https://user-images.githubusercontent.com/13365687/27041909-af88775a-4f95-11e7-9a72-ec35ec7e42b9.png)

**Comment by cadavre** [comment]
@metas-mk 

ad a.) It was my requirement to add notification. Without it user cannot be sure if bookmark was added. because of API call lag.

ad b.) It looks like browser-independent thing. I know there are few glitches in this navigation layouting that is not really about pure implementation but hack-fixing. TBA with browser-dependent fixes.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing/ Done.
