### ISSUE TITLE
Board w/ Swimlane type functionalities

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#833]
### Type of issue
Feature request
### Current behavior
Currently, we don't have the possibility to define a dashboard window w/ swimlane type functionalities.
### Expected behavior
Create such a window type for web UI, and allow to move the cards in the window between the lanes per drag&drop.

First rough ideas needed to be further detailed.

Belongs to https://github.com/metasfresh/metasfresh-webui-api/issues/432

**Comment by cadavre** [comment]
To be mocked and designed first.

@metas-mk do you feel you can "mock" single card view to have impression of what kind of fields will be displayed? Like probably: assignee (avatar or with full name?), title (1-2 lines?), description (4-5 lines?), some kind of "due date", tags?

**Comment by metas-mk** [comment]
@cadavre 
Here comes the first shot. As discussed, we will want to use this dashboard/ swimlane window in multiple functional environments, for example as project dashboard or as quotation/ prospect dashboard. The admin user will describe Dashboard Type/ Card Layout in Backend configuration windows and can then add these as single windows into menu w/ own name. Each dashboard will then be called with its own window ID. The cards layout will also be generic. It will have a header (link to the corresponding detail card window/ document), a generic text area with addition information, a label area and an avatar area.
The cards and lanes can be adjusted via drag and drop.

A rough idea how the window shall look like.
will sedribe his dashboard name and cards in a configuration window

**Comment by cadavre** [comment]
First question(s):

1. What shall happen on click on "label"?
2. Shall avatars link somewhere?
3. From where will come "title" text and "description" test? Will it be generated from backend document or it will be filled in "Add card" modal?
4. How document (with windowIs and docId) will be attached to card? Shall it happen somehow in "Add card" modal? Some kind of document search?

TODO in first place:

1. Mock and design dashboard with swimlane.
2. Mock and design modal for "Add card".

After TODO no.1 and no.2 we can start with static implementation.

**Comment by teosarca** [comment]
IMHO we shall develop a whole new concept, not related with "window"s.

1. dunno, i guess the document shall opened (similar to zoom into)
2. 3. I think shall be part of the JSON responses that backend shall provide. i.e. we shall define the Lane(s) and  Card(s) data model and also REST endpoint to get/manipulate the cards and lanes.
4. Usually, i think the cards will be already there because the information is already there (i.e. basically the Lanes are nothing more than segmenting and presenting the data in a different way).
In case we would need to add Cards i would suggest to have a similar endpoint like the typeahead.

**Comment by metas-mk** [comment]
@cadavre 
> 1. What shall happen on click on "label"?
--> the corresponding document/ record opens (e.g. sales order, project issue ...)

> 2. Shall avatars link somewhere?
--> Yes, I would say shall link to a special user page with "public" information about the user (email, phone, department, ...)

>3. From where will come "title" text and "description" test? Will it be generated from backend document or it will be filled in "Add card" modal?
--> Agree w/ teo: I think shall be part of the JSON responses that backend shall provide. i.e. we shall define the Lane(s) and Card(s) data model and also REST endpoint to get/manipulate the cards and lanes.

> 4. How document (with windowIs and docId) will be attached to card? Shall it happen somehow in "Add card" modal? Some kind of document search?
--> Agree w/ teo: Cards will be there. The user can select the cards and drag/ drop in lanes.

**Comment by cadavre** [comment]
Ad 1) @teosarca @metas-mk – not "title", but "label" (or "tag"). :)

**Comment by teosarca** [comment]
> Ad 1) @teosarca @metas-mk – not "title", but "label" (or "tag"). :)

same, i would say, shall be part of API responses.

**Comment by cadavre** [comment]
![zrzut_ekranu_2017-06-07_o_10_17_10](https://user-images.githubusercontent.com/461796/26868992-1a7b4ec2-4b6b-11e7-8825-ca1e49f11883.jpg)

We have title linked to particular document (eg. sales order, issue).

#1 – shall be linked to the same place as title then (as you answered)? Or probably maybe "filter" dashboard swimlanes for only selected labels or somehow?
#2 – as commented: "shall link to a special user page with "public" information about the user"

**Comment by metas-mk** [comment]
@cadavre labels will not have a link in the first step. just shown.

**Comment by cadavre** [comment]
OK, roger. So also in first step there will be no "Add card" because we would need then to add some possibility to "search document to link", though now we create cards from previously generated data (sales orders etc.). Is that correct?

**Comment by teosarca** [comment]
hi @cadavre 

> OK, roger. So also in first step there will be no "Add card" because we would need then to add some possibility to "search document to link"

True.


> though now we create cards from previously generated data (sales orders etc.). Is that correct?
This assumption is no longer correct, but won't affect the frontend anyways.
For the first working increment (WI) we will define the lanes in application dictionary.

**Comment by metas-mk** [comment]
@teosarca @cadavre 

> OK, roger. So also in first step there will be no "Add card" because we would need then to add some possibility to "search document to link"
> True.

Sorry, did not understand this one. We need a possibility to add cards that were predefined via application dictionary. How shall the user add cards to the lane without having an "add cards" functionality?

**Comment by teosarca** [comment]
@metas-mk  right, sorry, when i've answered i was thinking to "Add lane".

**Comment by metas-mk** [comment]
@teosarca ok, thanks. Yes, that's right. We don't need "Add lane" in the beginning.
@cadavre We need "Add cards" functionality from the beginning.

**Comment by cadavre** [comment]
Hah, ok. ;)

Then I need to ask you about some feedback about how "Add card" modal will look like? Would it be regular "document"/"action" form generated by already-known WebUI generator we use everywhere? In short: generated by API, rendered by frontend?

**Comment by metas-mk** [comment]
@cadavre @teosarca 
Currently, I'm thinking about something like the sidelist component + additional drag&drop behavior. A list of card elements that the user can open when pressing "add cards". The list can be sorted/ filtered. The user can drag the card to a lane and drop there. On the card itself, there is a possibility to remove the card from the dashboard.
The list shall come from API, rendered by frontend,

WDYT?

**Comment by teosarca** [comment]
Update: API (first working prototype) is available.
See http://w101.metasfresh.com:8081/swagger-ui.html#/board-rest-controller

And more, i've also introduced a websocket endpoint for each board.
On that endpoint the server will send change notifications when:
* a card was added
* a card was removed
* a card was changed (e.g. moved from one lane to another)

IMHO it's important to use the websockets from very beginning because Boards are something interactive used by concurrent users and when a user is adding/removing/changing a card, that change shall be instantly visible to all other users.

I am open to suggestions.

**Comment by teosarca** [comment]
Additionally, i've introduced another menu type called "board". When user is clicking on a menu item of type "board", the frontend shall open that Board.

**Comment by teosarca** [comment]
Pls ping me when ready to kickstart this one.

**Comment by cadavre** [comment]
First designs for swimlane:
![swimlane](https://user-images.githubusercontent.com/461796/27026313-9bb60d06-4f5d-11e7-8128-b18d655769de.png)

Drag&drop animation: https://youtu.be/voHfES335pc

Still waiting for sidebar with cards when "Adding cards". BTW We include filters in cards sidebar, right?

**Comment by teosarca** [comment]
> Still waiting for sidebar with cards when "Adding cards". BTW We include filters in cards sidebar, right?

It's already delivered. Frontend shall just call  [GET /rest/api/board/{boardId}/newCardsVie](http://w101.metasfresh.com:8081/swagger-ui.html#!/board-rest-controller/getUsingGET) endpoint  which will create an return a view.
Frontend shall handle it as a side list (view) using the regular view API.

**Comment by cadavre** [comment]
@teosarca I was taking about designs not backend requirements. :)

![swimlines sidebar](https://user-images.githubusercontent.com/461796/27043088-4cd27be8-4f99-11e7-8adb-4911bc2db7ca.png)

What are requirements for sidebar? Search bar? Filters? I guess both would work only if you could utilize search engine?

**Comment by damianprzygodzki** [comment]
Note from @metas-mk:
- remove the space between description and label to do not waste room there.

**Comment by teosarca** [comment]
@damianprzygodzki  i think the development for this one can start because the only thing which is missing from API is the endpoint which provides the cards to be added.
But there is an API for actually adding a card.

Ofc, in meantime i will prepare the backend.

wdyt?

**Comment by teosarca** [comment]
Board API changes (please check swagger for details)
* /rest/api/board/{boardId}/newCardsView/* endpoints for creating and managing the "cards available to be added" view

It will be available on next rollout

**Comment by damianprzygodzki** [comment]
Tested only on `/board/540000` - one available and delivered board. Filters are not integrated because in `view` there was none of them presented.

2nd missing thing, now updates of lanes are made in a sync way - because WS events messages are pretty useless. Please provide something like in other cases, not only IDs, but whole data objects that was changed.

So in case of `laneCardsChanged` event, provide changed cards (when card is added we need whole new card object).

My proposition is to get rid of that event and separate actions on more events like:
- laneCardsAdded (whole new objects)
- laneCardsRemoved (only ids would be enough)
- laneCardsSorted (only ids would be enough)
and so on.

**Comment by teosarca** [comment]
Let's talk tomorrow, but if i understood it right, i am tempt to agree.

**Comment by teosarca** [comment]
Quick tested, first issue found: cannot open the board from menu, i.e. following does nothing
![image](https://user-images.githubusercontent.com/1244701/27334731-e2e224e6-55d2-11e7-9d31-ea21621005bc.png)

**Comment by teosarca** [comment]
Another issue: cannot add a card as last in a lane.
![image](https://user-images.githubusercontent.com/1244701/27334911-7e8f22e0-55d3-11e7-889b-63250e2efb18.png)

**Comment by teosarca** [comment]
Another thing: when user presses the "Add new" button pls always call "GET .../{boardId}/newCardsView" endpoint. Atm the endpoint it's called only first time user is pressing the "Add new" button.

**Comment by damianprzygodzki** [comment]
> Another thing: when user presses the "Add new" button pls always call "GET .../{boardId}/newCardsView" endpoint. Atm the endpoint it's called only first time user is pressing the "Add new" button.

So each time we are opening sidelist we should create new viewId? What about filters? They should disappear?

**Comment by teosarca** [comment]
> So each time we are opening sidelist we should create new viewId?
Yes... else the internal index is not created so records added after user presses "Add new" won't be available as cards.

> What about filters? They should disappear?
1. I have to check why the filters are not provided... they should
2. Yes, in case there are filters we need them rendered same as on any view.

**Comment by damianprzygodzki** [comment]
So what is the point of viewId here? If there can be only one instance at once?

**Comment by teosarca** [comment]
it's not only one instance. think about concurrent users each of them adding cards...
And more, when we will have filters, the need of viewId will become much more obvious.

Ahhh, and I think this is also answering the question/suggestion you had somewhere above.
"Why we need websockets instead of providing the result in response?"
Exactly because board is a collaborative tool, so when someone is changing the board everybody shall see it.

**Comment by teosarca** [comment]
Another thing: At the moment, when i am adding a new card (i.e. i am dragging it from "Add cards" panel and dropping it to some lane), the card is not removed from the "Add cards" panel.

This issue can be solved on frontend side or on backend side.

If possible, i would suggest to solve it on frontend side because it's easier/quickest.
If we decide to solve it on backend side, we shall change the "add card" endpoint and in request we also need the viewId from where the card was dragged. Backend would add the card and after that would fire a websocket event about the viewId which was changed.

**Comment by damianprzygodzki** [comment]
> This issue can be solved on frontend side or on backend side.

Yeah, no problem for me. I can remove them.

> Ahhh, and I think this is also answering the question/suggestion you had somewhere above.

I hadn't actually. Maybe someone other. No problem for me with WS. They are implemented already. Just said that events messages are tough to process.

**Comment by teosarca** [comment]
About the websocket event changes, i thought a bit....

Initially i was thinking to something similar to your suggestion, but,

>  laneCardsAdded (whole new objects)

* i cannot provide the whole object via websocket because i don't know the language of the listener and there might be different listeners with different languages.
* it would be nice to also provide the ordered cardIds to let the frontend precisely insert the card in the right place. Also because we provide the ordered cardIds, as a piggybacking, frontend can use this opportunity to make sure the whole lane it's in good shape (in terms of cards ordering)

> laneCardsRemoved (only ids would be enough)

Yup in this case would be fine to provide only the removed cardId

> laneCardsSorted (only ids would be enough)

Yup, actually that's what the "laneCardsChanged" event is providing.

----

After checking which are the benefits of having all those events, at that time, i've decided that the laneCardsChanged(cards order changed) we need it anyways and basically it also solves the problem for adding and removing too.

wdyt?

**Comment by teosarca** [comment]
Another issue: re-arranging the cards in the same lane not working.

the API call shall be something like 
```
curl -X PATCH --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[ \ 
   { \ 
     "op": "replace", \ 
     "path": "position", \ 
     "value": 0 \ 
   } \ 
 ]' 'http://localhost:8080/rest/api/board/540000/card/1003533'
```

"position" is used to set the card position in a lane. It's a zero based index.
e.g.
* position=0 => first card in the lane
* position=1 => second card in the lane
* position=2 => third card in the lane
* etc

----

Also, while issuing that command from swagger, i observed that the board was not updated Even though the websocket event was sent.

**Comment by teosarca** [comment]
Another one: Adding a card in the middle: when dropping it, it will added to the bottom.
Checked API calls, they are OK.
But just the frontend is not adding it to the right position.
More, a websocket event was also fired to comunicate the orderder cardIds in the lane but was not considered.


![image](https://user-images.githubusercontent.com/1244701/27342390-b9d66006-55e8-11e7-8448-0e1c5f3762a4.png)

![image](https://user-images.githubusercontent.com/1244701/27342507-177a7bd4-55e9-11e7-9895-382a71668c96.png)

**Comment by teosarca** [comment]
Another one: make the card title a link.

![image](https://user-images.githubusercontent.com/1244701/27346069-9d086eea-55f4-11e7-8030-0f96d7fcee8f.png)

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/27346868-39b22afe-55f7-11e7-8b51-ba77147f570e.png)

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/27347160-3c2e932a-55f8-11e7-9532-6a910828b239.png)

**Comment by teosarca** [comment]
Another issue: board is not refreshed on language changed event.

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/27352161-622e497a-5608-11e7-813b-4cc08dcca1b4.png)

**Comment by damianprzygodzki** [comment]
First of all could you write down all of events that are provided?

**Comment by teosarca** [comment]
> @teosarca First of all could you write down all of events that are provided?

There just to path(s) available: laneId and position.

> Okay. So it will be only for sorting.
>
> Adding new card and removing will be handled by response - i can't see other solution if you don't want to provide new events - i can't go back and forth in array and checks if something other changed in cards.

I can provide the cardId which was added but how would you know on which position to insert the card?
What if multiple users are changing the board at the same time? How would you manage to have the right order?

**Comment by damianprzygodzki** [comment]
> @teosarca First of all could you write down all of events that are provided?
> There just to path(s) available: laneId and position.

Soo what is the language changed event.
> Another issue: board is not refreshed on language changed event.
Do you mean, language change in MasterWindow WS? But board is not MasterWindow, so how it should refresh itself?

---

The problem is that taking data from two different protocols will cause race condition.

I have to somehow get added object, and position. And we have to choose:
-or we are going to use `laneCardsChanged` event msg, and then i will fetch the card from API (additional GET card endpoint is needed)
-or we are going to provide in response position, and for other user just notify that `THIS VIEW HAS CHANGED. REFRESH`

**Comment by teosarca** [comment]
> Soo what is the language changed event.

AFAIK, a websocket event is sent to /userSession/<userId> endpoint and you are/should listen to that endpoint already.

----

> The problem is that taking data from two different protocols will cause race condition.

Ok, what i wrote in some messages above it was my protocol design trying to figure out what frontend would need in order to work:
* when a user is changing something in dashboard
* all dashboard changes shall be propagated to everybody who is using the dashboard (websockets)
* have a way to accurately keep everybody in sync
* avoid sending board full refresh events which might make the board flicker (flickering is a think we want to avoid by all means)

It's OK and i am open to any suggestions which would solve all the requirements.
Might be that instead me guessing what frontend would need in order work nice and efficient, it would be much more accurate if you would do those specifications.
wdyt?

**Comment by teosarca** [comment]
Update:
* get cards by cardIds endpoint: http://w101.metasfresh.com:8081/swagger-ui.html#!/board-rest-controller/getCardsUsingGET
* deprecated http://w101.metasfresh.com:8081/swagger-ui.html#!/board-rest-controller/createNewCardsView_DEPRECATEDUsingGET . Please use the "POST" variant.

**Comment by damianprzygodzki** [comment]
@teosarca I've received such an error and now cannot load board at all:

```
Keine Datenbank-Verbindung: Connections could not be acquired from the underlying database!
```

**Comment by teosarca** [comment]
Note: i've quick checked on w101 and found following issue: when adding the same KPI twice or more, only one of them it's actually rendered.
(Somehow it seems like frontend it's indexing by "kpiId" instead of indexing by "itemId"....)

![image](https://user-images.githubusercontent.com/1244701/27535951-8f6f4b66-5a75-11e7-8f0b-d7547bf00418.png)

**Comment by damianprzygodzki** [comment]
> Note: i've quick checked on w101 and found following issue: when adding the same KPI twice or more, only one of them it's actually rendered.

Wrong issue. Besides that its solved.

**Comment by teosarca** [comment]
Thanks.  Do you know which was the commit that fixed it?
Asking because we need to link it to this issue.

**Comment by metas-mk** [comment]
Started Testing.

a) Layout looks broken. Why is the horizontal scrollbar in the middle of the screen? Please make it 100% height like in our other windows.
![image](https://user-images.githubusercontent.com/13365687/27655789-dd4ed3ce-5c46-11e7-860f-966c48cc3321.png)

b) Header Link in cards. Don't open in the same window. Open in new Browser tab.

c) Draging existing card from top of stack to the bottom gives an error.
![image](https://user-images.githubusercontent.com/13365687/27655956-8cfe8274-5c47-11e7-9b4e-b5d32f9366c4.png)

d) Cards too wide. Pls check how 6 Lanes fit in 100% width. Should still look good and will reduce the annoying horizontal scroll.


Further Tests to come.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required and discussed for now. Further Issues will be solved in follow-up issues. Closing/ Done.l
