### ISSUE TITLE
table and columns window is empty

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#870]
### Type of issue
Bug
### Current behavior
when you open table and columns window nothing happens
### Expected behavior
table and columns window should open or at least see an error why it doesn't work
### Steps to reproduce
1. login as sysadmin
2. go to menu and open for e.g. Element window (id 151) => you'll see entries 
3. go to menu and open Tabelle und Spalte (id 100) => no errors, and it's still Element window NOK
4. refresh => no errors, window is empty NOK
5. open Element again => window is empty  NOK 

**Window:** 151, 100, 151 again

**Comment by damianprzygodzki** [comment]
Looks like wrong configuration. Both table layout and table data should have property `fields` filled because the sorting and the widget display is impossible.

The bug is here:
<img width="380" alt="screen shot 2017-06-12 at 13 48 25" src="https://user-images.githubusercontent.com/5701744/27032598-e8c3ed9e-4f75-11e7-8493-fb8ee410b123.png">

So, nothing to do with that on front end side. @metas-lc Can we close that issue?

**Comment by teosarca** [comment]
Hi @damianprzygodzki  ,

I didn't get it, might be that i have tomatoes in my eyes, but i cannot see it. Can you pls describe the issue a bit more.

Thanks

**Comment by damianprzygodzki** [comment]
<img width="687" alt="screen shot 2017-06-12 at 14 07 22" src="https://user-images.githubusercontent.com/5701744/27033202-9dea1cb4-4f78-11e7-8b1f-228dec4a805b.png">

http://w101.metasfresh.com:8081/rest/api/documentView/100/layout?viewType=grid&supportTree=true

the upper one is valid, the one below is not.

**Comment by teosarca** [comment]
update: fixed on server side.

Note to IT: if the problem persists, pls create a backend task for now.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* Opening Element  works fine
* Opening  tabelle un spalte works fine.
* Windows have the correct number
* Also fine after refresh.
