### ISSUE TITLE
Automatic Testing Framework for Frontend

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#894]
### Type of issue
Feature request
### Current behavior
Currently, there is no automatic Testing Framework used for Frontend Development.
### Expected behavior
Implement and use an Automatic Testing Framework for Frontend. The tests shall be integrated into the Build & Rollout Process.
The same or similar Framework shall be uses or Rest_API testing too.

**Comment by cadavre** [comment]
Is it fine for you to provide Docker-based testing environment? Do you want to integrate testing on your CI or on GitHub (it might be hard to find existing integration)?

**Comment by cadavre** [comment]
I'm after some talks with @tomaszfryc about first implementation of automated tests.

We decided to start with functional components tests, i.e. test lookup for common and assumed functionality like "when I input >ab< I get suggestions for all >Ab...< data", "when I click 2nd field with mouse I get suggestions opened for this field".

For all front-end automated tests we need actually a screen on headless machines. We achieve it by using `xvfb` with `Fluxbox` and installed browser or ready-made Docker package.

Actually good thing is that we use Selenium as an automation tool. This is pretty all of our stack we use regularly:

* Cucumber (BDD to define test steps)
* Selenium standalone server
* Chimp (JS testing framework)
* Chimp Webdriver for Selenium

This works pretty much like this:

1. Install Chimp package with `npm install`.
2. Run `bin/chimp`.
3. Now Chimp is using Webdriver to connect to standalone Selenium.
4. Chimp is running test by test.
5. At the end Chimp is generating `output.json` with test results.

Question is: what do you think about above stack? If accepted – how do you feel about running Selenium? You can have one single instance installed somewhere or run Selenium standalone package for headless servers with Docker on each Jenkins build. https://hub.docker.com/r/selenium/standalone-chrome/
It doesn't matter for us because we only provide configuration with host and port for Selenium.

Also required: you need to deploy somewhere (with accessible URL, might by private network) each built version that you want to test, so we can run tests on it.

**Comment by metas-ts** [comment]
Hi, here are some preliminary thoughts
* I guess you will sortof instrument the js-stuff in metasfresh-webui-frontend to give those thingies meaningfull names and make them "addressable" from selenium, right?
* functional component tests sounds very good..i imagine a library of "low-level" tests that can be run stand alone, but at the same time provides the building blocks for more complex tests.
* we have very little experience with all this stuff..for example, so far, I suspect that I don't really understand what chimp actually does...but I guess we will see it when you make a prototype and start to tackle those low-level component tests.

> Question is: what do you think about above stack? If accepted – how do you feel about running Selenium? 
[...]
> Also required: you need to deploy somewhere (with accessible URL, might by private network) each built version that you want to test, so we can run tests on it.

I would say let's get started :-) 
We could first play on w101, or we could provide a dedicated instance..we could e.g. install docker on it and run that dockerized selenium you mentioned, or whatever fits best..and then we could roll out whatever branch we want onto that instance (with a vanilla database) and fire up chimp to run the tests against it. Those tests that chimp runs are also in some git repo, right? 
If this can be make to work from the command line (particularly the stuff *after* the rollout), i'm sure that we can automate the whole process.

For the longer run, I would like to outline the following:
* our goal is to is to have a framework in which we can write high level-tests without the need for "technical" knowledge.. "functional" knowledge should suffice.
  * ..like "log in with a certain user name an password", "create a bpartner", "create a sales order with this and this product", "verify grandtotal=99€" etc etc
  * the goal is that we all can push test specs into a repository, rather than asking an expert to implement a particular test
* in early 2016 looked into BDD frameworks and at the time felt that cucumber was a bit "unflexible" for my needs..
   To be more concrete: if we talk about the test you mentioned 
   "when I input >ab< I get suggestions for all >Ab...< data", 
i guess cucumber is well suited, but for a complex end2end test that includes many different steps (e.g. creating products and prices that are later used in sales and purachase orders) i ended up using [concordion](http://concordion.org/).
With concordion, we could basically write a feature- or workflow-documentation in html or markdown and enrich that text with special tags that invoke the test fixture code. I'm assuming here, that we can drive selenium with java code and be able to do the same things you can do when driving selenium with javascript fixture code (is that correct?). 
With building blocks from the low-level tests, we could then write any test without developer knowledge...only when the framework is extended, our testers need new building blocks.
* the same spec can be run against the full metasfresh stack, or aginst the webui-api (bypassing the frontend)

But for "now" and for the functional component tests, i guess cucumber is great anyways..and, let's see how far we get with cumber..maybe I just didn't understand it...if we hit the limits if we use it according to your expertise.

**Comment by teosarca** [comment]
closing this one.
further work was done on https://github.com/metasfresh/metasfresh-webui-frontend/issues/1260.
