### ISSUE TITLE
Add/ Remove KPI Widget functionality for User Dashboard

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#905]
### Type of issue
Feature request
### Current behavior
Currently, the User Dashboard is static. The Widgets are shown and can only by moved, but not removed and not added.
### Expected behavior
Similar to the new Dashboard/ Swimland Functionality, a functionality shall be provided for the user to add/ remove KPI widgets from the board.
![image](https://user-images.githubusercontent.com/13365687/27250481-6b7f721c-5331-11e7-8bc2-59aaacb7826d.png)

**Comment by teosarca** [comment]
We need to prepare the API first.

**Comment by teosarca** [comment]
NOTE: as discussed, i've unified GET /kpis/available and GET /targetIndicators/available.
See https://github.com/metasfresh/metasfresh-webui-api/issues/464 .
Will be available on next rollout.

**Comment by damianprzygodzki** [comment]
From endpoints:
POST /rest/api/dashboard/targetIndicators/new 
POST /rest/api/dashboard/kpis/new
I am getting:
```
"exception": "de.metas.ui.web.exceptions.EntityNotFoundException"
```

**Comment by teosarca** [comment]
checking....

**Comment by teosarca** [comment]
fixed, shall work now.

**Comment by damianprzygodzki** [comment]
@teosarca How can we set position of widget when adding new one?

**Comment by teosarca** [comment]
we can't :(

I am thinking to add "position" field on
http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/addKPIItemUsingPOST
and
http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/addTargetIndicatorItemUsingPOST

wdyt?

**Comment by teosarca** [comment]
Update: on https://github.com/metasfresh/metasfresh-webui-api/issues/474 i've implemented:
* support for adding an KPI/target indicator on a given position
* websocket support (all changes are notified to websockets, simiar with Board API)
* patching support for a given KPI/target indicator => not needed in this task

**Comment by damianprzygodzki** [comment]
Let me know when it be integrated.

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/474 is rolleded out. API shall be available on w101

**Comment by teosarca** [comment]
Quick checked to change KPIs order (same issue on target indicators too).

![image](https://user-images.githubusercontent.com/1244701/27578846-0a8d79fe-5b2e-11e7-9ccb-6dc0e2c2c69e.png)


The problem is with that endpoint call.
When patching a KPI/target indicator, there is no "position" field. Because changing the position for one KPI implies changing the position on all others.
For that reason, the "position" path is not supported.

To change the order of KPIs or target indicators, please use:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeKPIsDashboardUsingPATCH
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeTargetIndicatorsDashboardUsingPATCH

The PATCH request body shall look like:
```json
[
  {
    "op": "replace",
    "path": "orderedItemIds",
    "value": { itemId1, itemId2 .... itemIdLast}
  }
]
```

**Comment by damianprzygodzki** [comment]
As discussed on skype: we should somehow unify `board` and `dashboard` behavior. So or we are going to use that way of replacing property "orderedItemIds", or change "position" property for both entities.

**Comment by teosarca** [comment]
checking

**Comment by teosarca** [comment]
UPDATE: implemented "position" support in https://github.com/metasfresh/metasfresh-webui-api/issues/486
Will be available on next rollout.

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest

Adding and removing KPI widgets works correcty in webui.
Stress-tested and had no problems either.
