### ISSUE TITLE
Refactor/unify Menu and Sitemap

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#930]
### Type of issue
Feature request

### Current behavior
In the past we had several issues where the Sitemap behaviour is different from Menu behaviour.
A recent one is this: https://github.com/metasfresh/metasfresh-webui-frontend/issues/926 .

### Expected behavior
It seems like different code is handling the Sitemap and Menu.
We shall avoid this because it's just a source for more bugs.

Not sure how much can be refactored but at least the code which is handling what shall happen when user presses on a menu item shall be the same.

**Comment by damianprzygodzki** [comment]
If you have something in mind, how the refactor should be made, please share with us.

**Comment by teosarca** [comment]
e.g. the code that determines what shall happen when a user clicks on a menu item shall be the same.

But i am just guessing, the main focus of this task shall be what to do make "menu" and "sitemap" share more logic.
That would make that part of the code not so fragile and would avoid trivial bugs when adding a new menu item type or changing the behaviour of a menu item type.

**Comment by damianprzygodzki** [comment]
They are builded that way, because of lack of initial assumption.

If you want, we can refactor that from the scratch - thats one and only idea to use the same thing at beginning.

And what would be nice, please rethink that, if for home menu, there was so many changes from designs and mocks, what about using the same behavior for both (menu & sitemap). Then in future we won't be in the same place as today - every change in behavior/look/functionality will be the same and there will be no ability to change something independent == no worries.

**Comment by wiadev** [comment]
1. We have MenuOverlayItem which incapsulates rendering of single item. No objections for this piece. Pretty straightforward implementation with sufficient level of customization via input properties.

2. We have MenuOverlay which incapsulates list of items (MenuOverlayItem) and adds search/filter capability. Also looks like adequate balance of responsibility between these components.

**Comment by metas-rc** [comment]
I am moving this task to done. 

While testing lately there were no differences noticed between menu and sitemap.
